/**
 * Static "featured tracks" snapshot — the last-resort catalog fallback.
 *
 * Rendered only when the live Jamendo API is unreachable AND the Postgres
 * catalog cache (`cached_tracks`) is empty, so the homepage never looks empty
 * or broken — the UI falls back to "Catalog is refreshing" copy plus this
 * curated seed list instead of a raw API error.
 *
 * Regenerate from real Jamendo data (replaces this file) by running:
 *
 *   npm run sync:featured
 *
 * This file is safe to overwrite — types and radios live in
 * `featured-types.ts` and `featured-radios.ts`.
 */

import type { FeaturedTrack } from "@/content/featured-types";

export const FEATURED_TRACKS: FeaturedTrack[] = [
  {
    id: "1860883",
    name: "The Secret Play",
    duration: 324,
    artistId: "artist-noonday-sun",
    artistName: "Noonday Sun",
    albumId: "376182",
    albumName: "",
    audioUrl: "https://prod-1.storage.jamendo.com/?trackid=1860883&format=mp31&from=app-devsite",
    downloadUrl: "https://mp3d.jamendo.com/download/track/1860883/mp32/",
    image: "https://usercontent.jamendo.com/?type=album&id=376182&width=300&trackid=1860883",
    imageSmall: "https://usercontent.jamendo.com/?type=album&id=376182&width=300&trackid=1860883",
    licenseName: null,
    genre: "trap",
    bpm: 140,
    speed: null,
    vocalInstrumental: null,
    tags: ["trap","synthesizer","drummachine","videogame","quirky"],
    popularityWeek: 0,
    popularityTotal: 0,
    listensTotal: 0,
    downloadsTotal: 0,
    releaseDate: null,
    audioDownloadAllowed: true,
  },
  {
    id: "2026816",
    name: "Vintage",
    duration: 211,
    artistId: "artist-cephas",
    artistName: "Cephas",
    albumId: "518760",
    albumName: "",
    audioUrl: "https://prod-1.storage.jamendo.com/?trackid=2026816&format=mp31&from=app-devsite",
    downloadUrl: "https://mp3d.jamendo.com/download/track/2026816/mp32/",
    image: "https://usercontent.jamendo.com/?type=album&id=518760&width=300&trackid=2026816",
    imageSmall: "https://usercontent.jamendo.com/?type=album&id=518760&width=300&trackid=2026816",
    licenseName: null,
    genre: "trap",
    bpm: 97,
    speed: null,
    vocalInstrumental: null,
    tags: ["trap","synthesizer","urban","peaceful"],
    popularityWeek: 0,
    popularityTotal: 0,
    listensTotal: 0,
    downloadsTotal: 0,
    releaseDate: null,
    audioDownloadAllowed: true,
  },
  {
    id: "2189073",
    name: "Coke | Trap Music",
    duration: 204,
    artistId: "artist-praz-khanal",
    artistName: "Praz Khanal",
    albumId: "574245",
    albumName: "",
    audioUrl: "https://prod-1.storage.jamendo.com/?trackid=2189073&format=mp31&from=app-devsite",
    downloadUrl: "https://mp3d.jamendo.com/download/track/2189073/mp32/",
    image: "https://usercontent.jamendo.com/?type=album&id=574245&width=300&trackid=2189073",
    imageSmall: "https://usercontent.jamendo.com/?type=album&id=574245&width=300&trackid=2189073",
    licenseName: null,
    genre: "trap",
    bpm: null,
    speed: null,
    vocalInstrumental: null,
    tags: ["trap","electroamplified","drummachine","urban","aggressive"],
    popularityWeek: 0,
    popularityTotal: 0,
    listensTotal: 0,
    downloadsTotal: 0,
    releaseDate: null,
    audioDownloadAllowed: true,
  },
  {
    id: "2265442",
    name: "JB",
    duration: 199,
    artistId: "artist-green-drumz",
    artistName: "Green Drumz",
    albumId: "",
    albumName: "",
    audioUrl: "https://prod-1.storage.jamendo.com/?trackid=2265442&format=mp31&from=app-devsite",
    downloadUrl: "https://mp3d.jamendo.com/download/track/2265442/mp32/",
    image: "https://upcdn.io/12a1yuy/image/prd/public/xOu63XloXE/q6cxNb6dLm2YQqh3y84H8.png",
    imageSmall: "https://upcdn.io/12a1yuy/image/prd/public/xOu63XloXE/q6cxNb6dLm2YQqh3y84H8.png",
    licenseName: null,
    genre: "trap",
    bpm: null,
    speed: null,
    vocalInstrumental: null,
    tags: ["trap","percussion","bass","drummachine","urban","neutral","dark"],
    popularityWeek: 0,
    popularityTotal: 0,
    listensTotal: 0,
    downloadsTotal: 0,
    releaseDate: null,
    audioDownloadAllowed: true,
  },
  {
    id: "1791060",
    name: "Sweethearth Beat|BM",
    duration: 190,
    artistId: "artist-shady",
    artistName: "Shady",
    albumId: "242728",
    albumName: "",
    audioUrl: "https://prod-1.storage.jamendo.com/?trackid=1791060&format=mp31&from=app-devsite",
    downloadUrl: "https://mp3d.jamendo.com/download/track/1791060/mp32/",
    image: "https://usercontent.jamendo.com/?type=album&id=242728&width=300&trackid=1791060",
    imageSmall: "https://usercontent.jamendo.com/?type=album&id=242728&width=300&trackid=1791060",
    licenseName: null,
    genre: "trap",
    bpm: 120,
    speed: null,
    vocalInstrumental: null,
    tags: ["trap","drums","bass","urban","dark","quirky"],
    popularityWeek: 0,
    popularityTotal: 0,
    listensTotal: 0,
    downloadsTotal: 0,
    releaseDate: null,
    audioDownloadAllowed: true,
  },
  {
    id: "2309877",
    name: "COBRA DS - Cash Explorer",
    duration: 180,
    artistId: "artist-cobra-ds",
    artistName: "Cobra Ds",
    albumId: "",
    albumName: "",
    audioUrl: "https://prod-1.storage.jamendo.com/?trackid=2309877&format=mp31&from=app-devsite",
    downloadUrl: "https://mp3d.jamendo.com/download/track/2309877/mp32/",
    image: "https://upcdn.io/12a1yuy/image/prd/public/2roUUupKee/rkd8ZZPSkmR5PWmkR3Hd1.png",
    imageSmall: "https://upcdn.io/12a1yuy/image/prd/public/2roUUupKee/rkd8ZZPSkmR5PWmkR3Hd1.png",
    licenseName: null,
    genre: "trap",
    bpm: null,
    speed: null,
    vocalInstrumental: null,
    tags: ["trap","dark","aggressive"],
    popularityWeek: 0,
    popularityTotal: 0,
    listensTotal: 0,
    downloadsTotal: 0,
    releaseDate: null,
    audioDownloadAllowed: true,
  },
  {
    id: "1879694",
    name: "Moonshot [Bouncy Trapwave Instrumental]",
    duration: 178,
    artistId: "artist-lofi-lopez",
    artistName: "Lofi Lopez",
    albumId: "452266",
    albumName: "",
    audioUrl: "https://prod-1.storage.jamendo.com/?trackid=1879694&format=mp31&from=app-devsite",
    downloadUrl: "https://mp3d.jamendo.com/download/track/1879694/mp32/",
    image: "https://usercontent.jamendo.com/?type=album&id=452266&width=300&trackid=1879694",
    imageSmall: "https://usercontent.jamendo.com/?type=album&id=452266&width=300&trackid=1879694",
    licenseName: null,
    genre: "trap",
    bpm: 120,
    speed: null,
    vocalInstrumental: null,
    tags: ["trap","synthesizer","abstract","quirky"],
    popularityWeek: 0,
    popularityTotal: 0,
    listensTotal: 0,
    downloadsTotal: 0,
    releaseDate: null,
    audioDownloadAllowed: true,
  },
  {
    id: "2260551",
    name: "Up And Down",
    duration: 178,
    artistId: "artist-vagabond-beatz",
    artistName: "Vagabond Beatz",
    albumId: "",
    albumName: "",
    audioUrl: "https://prod-1.storage.jamendo.com/?trackid=2260551&format=mp31&from=app-devsite",
    downloadUrl: "https://mp3d.jamendo.com/download/track/2260551/mp32/",
    image: "https://upcdn.io/12a1yuy/image/prd/public/1iMakTyfEt/O9Lpvq98e95AsreKcY6Ob.png",
    imageSmall: "https://upcdn.io/12a1yuy/image/prd/public/1iMakTyfEt/O9Lpvq98e95AsreKcY6Ob.png",
    licenseName: null,
    genre: "trap",
    bpm: null,
    speed: null,
    vocalInstrumental: null,
    tags: ["trap","energetic","aggressive"],
    popularityWeek: 0,
    popularityTotal: 0,
    listensTotal: 0,
    downloadsTotal: 0,
    releaseDate: null,
    audioDownloadAllowed: true,
  },
  {
    id: "2255968",
    name: "Team | Drill Music",
    duration: 178,
    artistId: "artist-praz-khanal",
    artistName: "Praz Khanal",
    albumId: "",
    albumName: "",
    audioUrl: "https://prod-1.storage.jamendo.com/?trackid=2255968&format=mp31&from=app-devsite",
    downloadUrl: "https://mp3d.jamendo.com/download/track/2255968/mp32/",
    image: "https://upcdn.io/12a1yuy/image/prd/public/CKJSeBs63R/sSmaPMsywjxg2oTcIAWAk.png",
    imageSmall: "https://upcdn.io/12a1yuy/image/prd/public/CKJSeBs63R/sSmaPMsywjxg2oTcIAWAk.png",
    licenseName: null,
    genre: "trap",
    bpm: null,
    speed: null,
    vocalInstrumental: null,
    tags: ["trap","percussion","urban","groovy"],
    popularityWeek: 0,
    popularityTotal: 0,
    listensTotal: 0,
    downloadsTotal: 0,
    releaseDate: null,
    audioDownloadAllowed: true,
  },
  {
    id: "2189062",
    name: "Sizzle | Trap Music",
    duration: 174,
    artistId: "artist-praz-khanal",
    artistName: "Praz Khanal",
    albumId: "",
    albumName: "",
    audioUrl: "https://prod-1.storage.jamendo.com/?trackid=2189062&format=mp31&from=app-devsite",
    downloadUrl: "https://mp3d.jamendo.com/download/track/2189062/mp32/",
    image: "https://upcdn.io/12a1yuy/image/prd/public/CKJSeBs63R/lCM6wr4Jf00yA3eM5GM8P.png",
    imageSmall: "https://upcdn.io/12a1yuy/image/prd/public/CKJSeBs63R/lCM6wr4Jf00yA3eM5GM8P.png",
    licenseName: null,
    genre: "trap",
    bpm: null,
    speed: null,
    vocalInstrumental: null,
    tags: ["trap","electroamplified","drummachine","urban","dark"],
    popularityWeek: 0,
    popularityTotal: 0,
    listensTotal: 0,
    downloadsTotal: 0,
    releaseDate: null,
    audioDownloadAllowed: true,
  },
  {
    id: "1999071",
    name: "Ambient Technology Trap",
    duration: 174,
    artistId: "artist-jackson-frost",
    artistName: "Jackson Frost",
    albumId: "508639",
    albumName: "",
    audioUrl: "https://prod-1.storage.jamendo.com/?trackid=1999071&format=mp31&from=app-devsite",
    downloadUrl: "https://mp3d.jamendo.com/download/track/1999071/mp32/",
    image: "https://usercontent.jamendo.com/?type=album&id=508639&width=300&trackid=1999071",
    imageSmall: "https://usercontent.jamendo.com/?type=album&id=508639&width=300&trackid=1999071",
    licenseName: null,
    genre: "trap",
    bpm: 135,
    speed: null,
    vocalInstrumental: null,
    tags: ["trap","synthesizer","vlog","peaceful","uplifting"],
    popularityWeek: 0,
    popularityTotal: 0,
    listensTotal: 0,
    downloadsTotal: 0,
    releaseDate: null,
    audioDownloadAllowed: true,
  },
  {
    id: "1888606",
    name: "Masked",
    duration: 173,
    artistId: "artist-beat-scientists",
    artistName: "Beat scientists",
    albumId: "456514",
    albumName: "",
    audioUrl: "https://prod-1.storage.jamendo.com/?trackid=1888606&format=mp31&from=app-devsite",
    downloadUrl: "https://mp3d.jamendo.com/download/track/1888606/mp32/",
    image: "https://usercontent.jamendo.com/?type=album&id=456514&width=300&trackid=1888606",
    imageSmall: "https://usercontent.jamendo.com/?type=album&id=456514&width=300&trackid=1888606",
    licenseName: null,
    genre: "trap",
    bpm: 143,
    speed: null,
    vocalInstrumental: null,
    tags: ["trap","synthesizer","urban","dark","peaceful"],
    popularityWeek: 0,
    popularityTotal: 0,
    listensTotal: 0,
    downloadsTotal: 0,
    releaseDate: null,
    audioDownloadAllowed: true,
  },
  {
    id: "2242740",
    name: "The Indian Dance House",
    duration: 172,
    artistId: "artist-jack-jack",
    artistName: "Jack Jack",
    albumId: "598513",
    albumName: "",
    audioUrl: "https://prod-1.storage.jamendo.com/?trackid=2242740&format=mp31&from=app-devsite",
    downloadUrl: "https://mp3d.jamendo.com/download/track/2242740/mp32/",
    image: "https://usercontent.jamendo.com/?type=album&id=598513&width=300&trackid=2242740",
    imageSmall: "https://usercontent.jamendo.com/?type=album&id=598513&width=300&trackid=2242740",
    licenseName: null,
    genre: "trap",
    bpm: null,
    speed: null,
    vocalInstrumental: null,
    tags: ["trap","synthesizer","travel","angry"],
    popularityWeek: 0,
    popularityTotal: 0,
    listensTotal: 0,
    downloadsTotal: 0,
    releaseDate: null,
    audioDownloadAllowed: true,
  },
  {
    id: "2026815",
    name: "Don't Wait",
    duration: 160,
    artistId: "artist-cephas",
    artistName: "Cephas",
    albumId: "518760",
    albumName: "",
    audioUrl: "https://prod-1.storage.jamendo.com/?trackid=2026815&format=mp31&from=app-devsite",
    downloadUrl: "https://mp3d.jamendo.com/download/track/2026815/mp32/",
    image: "https://usercontent.jamendo.com/?type=album&id=518760&width=300&trackid=2026815",
    imageSmall: "https://usercontent.jamendo.com/?type=album&id=518760&width=300&trackid=2026815",
    licenseName: null,
    genre: "trap",
    bpm: 120,
    speed: null,
    vocalInstrumental: null,
    tags: ["trap","synthesizer","peaceful"],
    popularityWeek: 0,
    popularityTotal: 0,
    listensTotal: 0,
    downloadsTotal: 0,
    releaseDate: null,
    audioDownloadAllowed: true,
  },
  {
    id: "2234445",
    name: "Urban Electronic Hip Hop Trap",
    duration: 158,
    artistId: "artist-soundbound",
    artistName: "SoundBound",
    albumId: "",
    albumName: "",
    audioUrl: "https://prod-1.storage.jamendo.com/?trackid=2234445&format=mp31&from=app-devsite",
    downloadUrl: "https://mp3d.jamendo.com/download/track/2234445/mp32/",
    image: "https://upcdn.io/12a1yuy/image/prd/public/bU7gVgBJR6/bBkgA6DUdvrLsuLAx86q1.png",
    imageSmall: "https://upcdn.io/12a1yuy/image/prd/public/bU7gVgBJR6/bBkgA6DUdvrLsuLAx86q1.png",
    licenseName: null,
    genre: "trap",
    bpm: null,
    speed: null,
    vocalInstrumental: null,
    tags: ["trap","drummachine","urban","energetic"],
    popularityWeek: 0,
    popularityTotal: 0,
    listensTotal: 0,
    downloadsTotal: 0,
    releaseDate: null,
    audioDownloadAllowed: true,
  },
  {
    id: "2316724",
    name: "Beneath The Surface",
    duration: 156,
    artistId: "artist-infraction",
    artistName: "Infraction",
    albumId: "",
    albumName: "",
    audioUrl: "https://prod-1.storage.jamendo.com/?trackid=2316724&format=mp31&from=app-devsite",
    downloadUrl: "https://mp3d.jamendo.com/download/track/2316724/mp32/",
    image: "https://upcdn.io/12a1yuy/image/prd/public/QqutgONqMa/Lc0c6B5IHOEeIzEslBP2X.png",
    imageSmall: "https://upcdn.io/12a1yuy/image/prd/public/QqutgONqMa/Lc0c6B5IHOEeIzEslBP2X.png",
    licenseName: null,
    genre: "trap",
    bpm: null,
    speed: null,
    vocalInstrumental: null,
    tags: ["trap","strings","bass","urban","happy","powerful","angry"],
    popularityWeek: 0,
    popularityTotal: 0,
    listensTotal: 0,
    downloadsTotal: 0,
    releaseDate: null,
    audioDownloadAllowed: true,
  },
  {
    id: "2189121",
    name: "Nude | UK Drill Music",
    duration: 155,
    artistId: "artist-praz-khanal",
    artistName: "Praz Khanal",
    albumId: "",
    albumName: "",
    audioUrl: "https://prod-1.storage.jamendo.com/?trackid=2189121&format=mp31&from=app-devsite",
    downloadUrl: "https://mp3d.jamendo.com/download/track/2189121/mp32/",
    image: "https://upcdn.io/12a1yuy/image/prd/public/CKJSeBs63R/6Fvs6joiGlFfdibuhL5J4.png",
    imageSmall: "https://upcdn.io/12a1yuy/image/prd/public/CKJSeBs63R/6Fvs6joiGlFfdibuhL5J4.png",
    licenseName: null,
    genre: "trap",
    bpm: null,
    speed: null,
    vocalInstrumental: null,
    tags: ["trap","percussion","electroamplified","drummachine","cymbal","urban","dark"],
    popularityWeek: 0,
    popularityTotal: 0,
    listensTotal: 0,
    downloadsTotal: 0,
    releaseDate: null,
    audioDownloadAllowed: true,
  },
  {
    id: "2138630",
    name: "Drill Trap Bass",
    duration: 155,
    artistId: "artist-joel-loopez",
    artistName: "Joel Loopez",
    albumId: "",
    albumName: "",
    audioUrl: "https://prod-1.storage.jamendo.com/?trackid=2138630&format=mp31&from=app-devsite",
    downloadUrl: "https://mp3d.jamendo.com/download/track/2138630/mp32/",
    image: "https://upcdn.io/12a1yuy/image/prd/public/cM4KyhObr1/5Ku68Ot8rvMLALhlq1l5g.png",
    imageSmall: "https://upcdn.io/12a1yuy/image/prd/public/cM4KyhObr1/5Ku68Ot8rvMLALhlq1l5g.png",
    licenseName: null,
    genre: "trap",
    bpm: null,
    speed: null,
    vocalInstrumental: null,
    tags: ["trap","electroamplified","drummachine","urban","dark","aggressive"],
    popularityWeek: 0,
    popularityTotal: 0,
    listensTotal: 0,
    downloadsTotal: 0,
    releaseDate: null,
    audioDownloadAllowed: true,
  },
  {
    id: "2287966",
    name: "Trap Slow",
    duration: 152,
    artistId: "artist-sergioproductions",
    artistName: "SergioProductions",
    albumId: "",
    albumName: "",
    audioUrl: "https://prod-1.storage.jamendo.com/?trackid=2287966&format=mp31&from=app-devsite",
    downloadUrl: "https://mp3d.jamendo.com/download/track/2287966/mp32/",
    image: "https://upcdn.io/12a1yuy/image/prd/public/OG0uaeCa87/jdN0LaIqJECZzG6Zd97bS.png",
    imageSmall: "https://upcdn.io/12a1yuy/image/prd/public/OG0uaeCa87/jdN0LaIqJECZzG6Zd97bS.png",
    licenseName: null,
    genre: "trap",
    bpm: null,
    speed: null,
    vocalInstrumental: null,
    tags: ["trap","strings","bass","urban","dark","sad"],
    popularityWeek: 0,
    popularityTotal: 0,
    listensTotal: 0,
    downloadsTotal: 0,
    releaseDate: null,
    audioDownloadAllowed: true,
  },
  {
    id: "1879007",
    name: "XXOC",
    duration: 151,
    artistId: "artist-hybrid-factory",
    artistName: "Hybrid Factory",
    albumId: "452641",
    albumName: "",
    audioUrl: "https://prod-1.storage.jamendo.com/?trackid=1879007&format=mp31&from=app-devsite",
    downloadUrl: "https://mp3d.jamendo.com/download/track/1879007/mp32/",
    image: "https://usercontent.jamendo.com/?type=album&id=452641&width=300&trackid=1879007",
    imageSmall: "https://usercontent.jamendo.com/?type=album&id=452641&width=300&trackid=1879007",
    licenseName: null,
    genre: "trap",
    bpm: 106,
    speed: null,
    vocalInstrumental: null,
    tags: ["trap","synthesizer","bass","crime","quirky"],
    popularityWeek: 0,
    popularityTotal: 0,
    listensTotal: 0,
    downloadsTotal: 0,
    releaseDate: null,
    audioDownloadAllowed: true,
  },
  {
    id: "2252709",
    name: "Wavy | Trap Soul Music",
    duration: 151,
    artistId: "artist-praz-khanal",
    artistName: "Praz Khanal",
    albumId: "",
    albumName: "",
    audioUrl: "https://prod-1.storage.jamendo.com/?trackid=2252709&format=mp31&from=app-devsite",
    downloadUrl: "https://mp3d.jamendo.com/download/track/2252709/mp32/",
    image: "https://upcdn.io/12a1yuy/image/prd/public/CKJSeBs63R/j3Wpxs5aQPIGx7su8NoEK.png",
    imageSmall: "https://upcdn.io/12a1yuy/image/prd/public/CKJSeBs63R/j3Wpxs5aQPIGx7su8NoEK.png",
    licenseName: null,
    genre: "trap",
    bpm: null,
    speed: null,
    vocalInstrumental: null,
    tags: ["trap","synthesizer","percussion","cymbal","urban","peaceful"],
    popularityWeek: 0,
    popularityTotal: 0,
    listensTotal: 0,
    downloadsTotal: 0,
    releaseDate: null,
    audioDownloadAllowed: true,
  },
  {
    id: "1936264",
    name: "Relapse | Dark Trap",
    duration: 149,
    artistId: "artist-uph-music",
    artistName: "UPH Music",
    albumId: "478951",
    albumName: "",
    audioUrl: "https://prod-1.storage.jamendo.com/?trackid=1936264&format=mp31&from=app-devsite",
    downloadUrl: "https://mp3d.jamendo.com/download/track/1936264/mp32/",
    image: "https://usercontent.jamendo.com/?type=album&id=478951&width=300&trackid=1936264",
    imageSmall: "https://usercontent.jamendo.com/?type=album&id=478951&width=300&trackid=1936264",
    licenseName: null,
    genre: "trap",
    bpm: 129,
    speed: null,
    vocalInstrumental: null,
    tags: ["trap","electricguitar","electroamplified","drama","dark"],
    popularityWeek: 0,
    popularityTotal: 0,
    listensTotal: 0,
    downloadsTotal: 0,
    releaseDate: null,
    audioDownloadAllowed: true,
  },
  {
    id: "2237570",
    name: "Aggressive Hip Hop Trap",
    duration: 148,
    artistId: "artist-soundbound",
    artistName: "SoundBound",
    albumId: "",
    albumName: "",
    audioUrl: "https://prod-1.storage.jamendo.com/?trackid=2237570&format=mp31&from=app-devsite",
    downloadUrl: "https://mp3d.jamendo.com/download/track/2237570/mp32/",
    image: "https://upcdn.io/12a1yuy/image/prd/public/bU7gVgBJR6/0wMEUdRNAWabUTbcIlHlK.png",
    imageSmall: "https://upcdn.io/12a1yuy/image/prd/public/bU7gVgBJR6/0wMEUdRNAWabUTbcIlHlK.png",
    licenseName: null,
    genre: "trap",
    bpm: null,
    speed: null,
    vocalInstrumental: null,
    tags: ["trap","synthesizer","electroamplified","travel","angry"],
    popularityWeek: 0,
    popularityTotal: 0,
    listensTotal: 0,
    downloadsTotal: 0,
    releaseDate: null,
    audioDownloadAllowed: true,
  },
  {
    id: "1863576",
    name: "PHONK TYPE BEAT",
    duration: 146,
    artistId: "artist-perycreep",
    artistName: "PeryCreep",
    albumId: "445347",
    albumName: "",
    audioUrl: "https://prod-1.storage.jamendo.com/?trackid=1863576&format=mp31&from=app-devsite",
    downloadUrl: "https://mp3d.jamendo.com/download/track/1863576/mp32/",
    image: "https://usercontent.jamendo.com/?type=album&id=445347&width=300&trackid=1863576",
    imageSmall: "https://usercontent.jamendo.com/?type=album&id=445347&width=300&trackid=1863576",
    licenseName: null,
    genre: "trap",
    bpm: 124,
    speed: null,
    vocalInstrumental: null,
    tags: ["trap","synthesizer","urban","dark","quirky"],
    popularityWeek: 0,
    popularityTotal: 0,
    listensTotal: 0,
    downloadsTotal: 0,
    releaseDate: null,
    audioDownloadAllowed: true,
  },
  {
    id: "2257712",
    name: "Powerful Brazilian Phonk",
    duration: 141,
    artistId: "artist-shedurumer",
    artistName: "SheduRumer",
    albumId: "",
    albumName: "",
    audioUrl: "https://prod-1.storage.jamendo.com/?trackid=2257712&format=mp31&from=app-devsite",
    downloadUrl: "https://mp3d.jamendo.com/download/track/2257712/mp32/",
    image: "https://upcdn.io/12a1yuy/image/prd/public/TAnY8V3Dek/J7RzRUlgOr5wPeOKayuWl.png",
    imageSmall: "https://upcdn.io/12a1yuy/image/prd/public/TAnY8V3Dek/J7RzRUlgOr5wPeOKayuWl.png",
    licenseName: null,
    genre: "trap",
    bpm: null,
    speed: null,
    vocalInstrumental: null,
    tags: ["trap","strings","bass","dark","energetic"],
    popularityWeek: 0,
    popularityTotal: 0,
    listensTotal: 0,
    downloadsTotal: 0,
    releaseDate: null,
    audioDownloadAllowed: true,
  },
  {
    id: "2149889",
    name: "Futuristic Dreamy Trap Beat",
    duration: 140,
    artistId: "artist-mokkamusic",
    artistName: "MokkaMusic",
    albumId: "",
    albumName: "",
    audioUrl: "https://prod-1.storage.jamendo.com/?trackid=2149889&format=mp31&from=app-devsite",
    downloadUrl: "https://mp3d.jamendo.com/download/track/2149889/mp32/",
    image: "https://upcdn.io/12a1yuy/image/prd/public/sEIluh3Ytu/YW9P7hEw66kWTZ3b1QC3k.png",
    imageSmall: "https://upcdn.io/12a1yuy/image/prd/public/sEIluh3Ytu/YW9P7hEw66kWTZ3b1QC3k.png",
    licenseName: null,
    genre: "trap",
    bpm: null,
    speed: null,
    vocalInstrumental: null,
    tags: ["trap","synthesizer","drummachine","atmospheric","groovy"],
    popularityWeek: 0,
    popularityTotal: 0,
    listensTotal: 0,
    downloadsTotal: 0,
    releaseDate: null,
    audioDownloadAllowed: true,
  },
  {
    id: "2317796",
    name: "Limbo City  - No Vocal Samples",
    duration: 140,
    artistId: "artist-databend",
    artistName: "Databend",
    albumId: "",
    albumName: "",
    audioUrl: "https://prod-1.storage.jamendo.com/?trackid=2317796&format=mp31&from=app-devsite",
    downloadUrl: "https://mp3d.jamendo.com/download/track/2317796/mp32/",
    image: "https://upcdn.io/12a1yuy/image/prd/public/s4nBIfQjNi/0cqByQkPwNq7xW7vxVRdN.png",
    imageSmall: "https://upcdn.io/12a1yuy/image/prd/public/s4nBIfQjNi/0cqByQkPwNq7xW7vxVRdN.png",
    licenseName: null,
    genre: "trap",
    bpm: null,
    speed: null,
    vocalInstrumental: null,
    tags: ["trap","synthesizer","drummachine","neutral"],
    popularityWeek: 0,
    popularityTotal: 0,
    listensTotal: 0,
    downloadsTotal: 0,
    releaseDate: null,
    audioDownloadAllowed: true,
  },
  {
    id: "2317795",
    name: "Limbo City",
    duration: 140,
    artistId: "artist-databend",
    artistName: "Databend",
    albumId: "",
    albumName: "",
    audioUrl: "https://prod-1.storage.jamendo.com/?trackid=2317795&format=mp31&from=app-devsite",
    downloadUrl: "https://mp3d.jamendo.com/download/track/2317795/mp32/",
    image: "https://upcdn.io/12a1yuy/image/prd/public/s4nBIfQjNi/XbJ9FOHu1nmPOP3Bo8KaO.png",
    imageSmall: "https://upcdn.io/12a1yuy/image/prd/public/s4nBIfQjNi/XbJ9FOHu1nmPOP3Bo8KaO.png",
    licenseName: null,
    genre: "trap",
    bpm: null,
    speed: null,
    vocalInstrumental: null,
    tags: ["trap","synthesizer","drummachine","neutral"],
    popularityWeek: 0,
    popularityTotal: 0,
    listensTotal: 0,
    downloadsTotal: 0,
    releaseDate: null,
    audioDownloadAllowed: true,
  },
  {
    id: "2266695",
    name: "In One Breath",
    duration: 139,
    artistId: "artist-riza-music",
    artistName: "RIZA music",
    albumId: "",
    albumName: "",
    audioUrl: "https://prod-1.storage.jamendo.com/?trackid=2266695&format=mp31&from=app-devsite",
    downloadUrl: "https://mp3d.jamendo.com/download/track/2266695/mp32/",
    image: "https://upcdn.io/12a1yuy/image/prd/public/T6pwpSVXhV/6U85Ir1WPu7xgT85m2RCD.png",
    imageSmall: "https://upcdn.io/12a1yuy/image/prd/public/T6pwpSVXhV/6U85Ir1WPu7xgT85m2RCD.png",
    licenseName: null,
    genre: "trap",
    bpm: null,
    speed: null,
    vocalInstrumental: null,
    tags: ["trap","synthesizer","urban","neutral","dark"],
    popularityWeek: 0,
    popularityTotal: 0,
    listensTotal: 0,
    downloadsTotal: 0,
    releaseDate: null,
    audioDownloadAllowed: true,
  },
  {
    id: "1876067",
    name: "Lucidity",
    duration: 139,
    artistId: "artist-sense404",
    artistName: "Sense404",
    albumId: "450662",
    albumName: "",
    audioUrl: "https://prod-1.storage.jamendo.com/?trackid=1876067&format=mp31&from=app-devsite",
    downloadUrl: "https://mp3d.jamendo.com/download/track/1876067/mp32/",
    image: "https://usercontent.jamendo.com/?type=album&id=450662&width=300&trackid=1876067",
    imageSmall: "https://usercontent.jamendo.com/?type=album&id=450662&width=300&trackid=1876067",
    licenseName: null,
    genre: "trap",
    bpm: 115,
    speed: null,
    vocalInstrumental: null,
    tags: ["trap","bass","bells","urban","quirky"],
    popularityWeek: 0,
    popularityTotal: 0,
    listensTotal: 0,
    downloadsTotal: 0,
    releaseDate: null,
    audioDownloadAllowed: true,
  },
  {
    id: "2056692",
    name: "Dark Phonk Beat",
    duration: 137,
    artistId: "artist-mit-rich",
    artistName: "Mit-Rich",
    albumId: "528817",
    albumName: "",
    audioUrl: "https://prod-1.storage.jamendo.com/?trackid=2056692&format=mp31&from=app-devsite",
    downloadUrl: "https://mp3d.jamendo.com/download/track/2056692/mp32/",
    image: "https://usercontent.jamendo.com/?type=album&id=528817&width=300&trackid=2056692",
    imageSmall: "https://usercontent.jamendo.com/?type=album&id=528817&width=300&trackid=2056692",
    licenseName: null,
    genre: "trap",
    bpm: null,
    speed: null,
    vocalInstrumental: null,
    tags: ["trap","synthesizer","bells","urban","dark"],
    popularityWeek: 0,
    popularityTotal: 0,
    listensTotal: 0,
    downloadsTotal: 0,
    releaseDate: null,
    audioDownloadAllowed: true,
  },
  {
    id: "1778248",
    name: "30 bucks",
    duration: 137,
    artistId: "artist-airplay",
    artistName: "Airplay",
    albumId: "",
    albumName: "",
    audioUrl: "https://prod-1.storage.jamendo.com/?trackid=1778248&format=mp31&from=app-devsite",
    downloadUrl: "https://mp3d.jamendo.com/download/track/1778248/mp32/",
    image: "https://upcdn.io/12a1yuy/image/prd/public/xMaoKmbwJr/HnA37ziv7e8G4Oz7yQl9s.png",
    imageSmall: "https://upcdn.io/12a1yuy/image/prd/public/xMaoKmbwJr/HnA37ziv7e8G4Oz7yQl9s.png",
    licenseName: null,
    genre: "trap",
    bpm: 85,
    speed: null,
    vocalInstrumental: null,
    tags: ["trap","synthesizer","drummachine","travel","neutral","dark","peaceful"],
    popularityWeek: 0,
    popularityTotal: 0,
    listensTotal: 0,
    downloadsTotal: 0,
    releaseDate: null,
    audioDownloadAllowed: true,
  },
  {
    id: "1832571",
    name: "Dark Beat",
    duration: 135,
    artistId: "artist-soulprodmusic",
    artistName: "SoulProdMusic",
    albumId: "199509",
    albumName: "",
    audioUrl: "https://prod-1.storage.jamendo.com/?trackid=1832571&format=mp31&from=app-devsite",
    downloadUrl: "https://mp3d.jamendo.com/download/track/1832571/mp32/",
    image: "https://usercontent.jamendo.com/?type=album&id=199509&width=300&trackid=1832571",
    imageSmall: "https://usercontent.jamendo.com/?type=album&id=199509&width=300&trackid=1832571",
    licenseName: null,
    genre: "trap",
    bpm: 107,
    speed: null,
    vocalInstrumental: null,
    tags: ["trap","electroamplified","drummachine","atmospheric","urban","dark","groovy"],
    popularityWeek: 0,
    popularityTotal: 0,
    listensTotal: 0,
    downloadsTotal: 0,
    releaseDate: null,
    audioDownloadAllowed: true,
  },
  {
    id: "2280578",
    name: "Neon",
    duration: 130,
    artistId: "artist-slxt-sync",
    artistName: "slxt sync",
    albumId: "",
    albumName: "",
    audioUrl: "https://prod-1.storage.jamendo.com/?trackid=2280578&format=mp31&from=app-devsite",
    downloadUrl: "https://mp3d.jamendo.com/download/track/2280578/mp32/",
    image: "https://upcdn.io/12a1yuy/image/prd/public/L1gcYhtACb/NVRan9UKecLgKOXKH8x4X.png",
    imageSmall: "https://upcdn.io/12a1yuy/image/prd/public/L1gcYhtACb/NVRan9UKecLgKOXKH8x4X.png",
    licenseName: null,
    genre: "trap",
    bpm: null,
    speed: null,
    vocalInstrumental: null,
    tags: ["trap","electroamplified","drummachine","videogame","neutral","dark","upbeat","energetic"],
    popularityWeek: 0,
    popularityTotal: 0,
    listensTotal: 0,
    downloadsTotal: 0,
    releaseDate: null,
    audioDownloadAllowed: true,
  },
  {
    id: "2311328",
    name: "Acid Attack",
    duration: 128,
    artistId: "artist-janevo",
    artistName: "Janevo",
    albumId: "",
    albumName: "",
    audioUrl: "https://prod-1.storage.jamendo.com/?trackid=2311328&format=mp31&from=app-devsite",
    downloadUrl: "https://mp3d.jamendo.com/download/track/2311328/mp32/",
    image: "https://upcdn.io/12a1yuy/image/prd/public/0RRtL4xu3P/Pg1hW9WBwzC3dwQfr2WQn.png",
    imageSmall: "https://upcdn.io/12a1yuy/image/prd/public/0RRtL4xu3P/Pg1hW9WBwzC3dwQfr2WQn.png",
    licenseName: null,
    genre: "trap",
    bpm: null,
    speed: null,
    vocalInstrumental: null,
    tags: ["trap","epic","aggressive"],
    popularityWeek: 0,
    popularityTotal: 0,
    listensTotal: 0,
    downloadsTotal: 0,
    releaseDate: null,
    audioDownloadAllowed: true,
  },
  {
    id: "2163420",
    name: "Driving Gaming Aggressive Phonk",
    duration: 126,
    artistId: "artist-mokkamusic",
    artistName: "MokkaMusic",
    albumId: "",
    albumName: "",
    audioUrl: "https://prod-1.storage.jamendo.com/?trackid=2163420&format=mp31&from=app-devsite",
    downloadUrl: "https://mp3d.jamendo.com/download/track/2163420/mp32/",
    image: "https://upcdn.io/12a1yuy/image/prd/public/sEIluh3Ytu/dJyc7nR3pqt5hjdLNKuGE.png",
    imageSmall: "https://upcdn.io/12a1yuy/image/prd/public/sEIluh3Ytu/dJyc7nR3pqt5hjdLNKuGE.png",
    licenseName: null,
    genre: "trap",
    bpm: null,
    speed: null,
    vocalInstrumental: null,
    tags: ["trap","synthesizer","cowbell","urban","aggressive"],
    popularityWeek: 0,
    popularityTotal: 0,
    listensTotal: 0,
    downloadsTotal: 0,
    releaseDate: null,
    audioDownloadAllowed: true,
  },
  {
    id: "2171578",
    name: "Futuristic Cyber Action Trap Midtempo",
    duration: 125,
    artistId: "artist-mokkamusic",
    artistName: "MokkaMusic",
    albumId: "",
    albumName: "",
    audioUrl: "https://prod-1.storage.jamendo.com/?trackid=2171578&format=mp31&from=app-devsite",
    downloadUrl: "https://mp3d.jamendo.com/download/track/2171578/mp32/",
    image: "https://upcdn.io/12a1yuy/image/prd/public/sEIluh3Ytu/7OkXDmggcqJIh0R9yCJ2E.png",
    imageSmall: "https://upcdn.io/12a1yuy/image/prd/public/sEIluh3Ytu/7OkXDmggcqJIh0R9yCJ2E.png",
    licenseName: null,
    genre: "trap",
    bpm: null,
    speed: null,
    vocalInstrumental: null,
    tags: ["trap","synthesizer","videogame","dark"],
    popularityWeek: 0,
    popularityTotal: 0,
    listensTotal: 0,
    downloadsTotal: 0,
    releaseDate: null,
    audioDownloadAllowed: true,
  },
  {
    id: "2280576",
    name: "Trapwave Overdrive",
    duration: 125,
    artistId: "artist-slxt-sync",
    artistName: "slxt sync",
    albumId: "",
    albumName: "",
    audioUrl: "https://prod-1.storage.jamendo.com/?trackid=2280576&format=mp31&from=app-devsite",
    downloadUrl: "https://mp3d.jamendo.com/download/track/2280576/mp32/",
    image: "https://upcdn.io/12a1yuy/image/prd/public/L1gcYhtACb/f2oKhIwKo8LrRcyGMMiNG.png",
    imageSmall: "https://upcdn.io/12a1yuy/image/prd/public/L1gcYhtACb/f2oKhIwKo8LrRcyGMMiNG.png",
    licenseName: null,
    genre: "trap",
    bpm: null,
    speed: null,
    vocalInstrumental: null,
    tags: ["trap","strings","piano","urban","neutral","dark","upbeat","energetic"],
    popularityWeek: 0,
    popularityTotal: 0,
    listensTotal: 0,
    downloadsTotal: 0,
    releaseDate: null,
    audioDownloadAllowed: true,
  },
  {
    id: "1990972",
    name: "FREE Drill Beat | Hip Hop Instrumental | Rap Beat",
    duration: 125,
    artistId: "artist-adi-rambo",
    artistName: "Adi Rambo",
    albumId: "504590",
    albumName: "",
    audioUrl: "https://prod-1.storage.jamendo.com/?trackid=1990972&format=mp31&from=app-devsite",
    downloadUrl: "https://mp3d.jamendo.com/download/track/1990972/mp32/",
    image: "https://usercontent.jamendo.com/?type=album&id=504590&width=300&trackid=1990972",
    imageSmall: "https://usercontent.jamendo.com/?type=album&id=504590&width=300&trackid=1990972",
    licenseName: null,
    genre: "trap",
    bpm: 140,
    speed: null,
    vocalInstrumental: null,
    tags: ["trap","guitar","bass","urban","dark"],
    popularityWeek: 0,
    popularityTotal: 0,
    listensTotal: 0,
    downloadsTotal: 0,
    releaseDate: null,
    audioDownloadAllowed: true,
  },
  {
    id: "1990811",
    name: "Chill Phonk",
    duration: 125,
    artistId: "artist-mit-rich",
    artistName: "Mit-Rich",
    albumId: "504521",
    albumName: "",
    audioUrl: "https://prod-1.storage.jamendo.com/?trackid=1990811&format=mp31&from=app-devsite",
    downloadUrl: "https://mp3d.jamendo.com/download/track/1990811/mp32/",
    image: "https://usercontent.jamendo.com/?type=album&id=504521&width=300&trackid=1990811",
    imageSmall: "https://usercontent.jamendo.com/?type=album&id=504521&width=300&trackid=1990811",
    licenseName: null,
    genre: "trap",
    bpm: 140,
    speed: null,
    vocalInstrumental: null,
    tags: ["trap","synthesizer","atmospheric","peaceful"],
    popularityWeek: 0,
    popularityTotal: 0,
    listensTotal: 0,
    downloadsTotal: 0,
    releaseDate: null,
    audioDownloadAllowed: true,
  },
  {
    id: "2163418",
    name: "Dark Trap Percussion Beat",
    duration: 123,
    artistId: "artist-mokkamusic",
    artistName: "MokkaMusic",
    albumId: "",
    albumName: "",
    audioUrl: "https://prod-1.storage.jamendo.com/?trackid=2163418&format=mp31&from=app-devsite",
    downloadUrl: "https://mp3d.jamendo.com/download/track/2163418/mp32/",
    image: "https://upcdn.io/12a1yuy/image/prd/public/sEIluh3Ytu/8PjDuxNODk5ikMxaYnh2c.png",
    imageSmall: "https://upcdn.io/12a1yuy/image/prd/public/sEIluh3Ytu/8PjDuxNODk5ikMxaYnh2c.png",
    licenseName: null,
    genre: "trap",
    bpm: null,
    speed: null,
    vocalInstrumental: null,
    tags: ["trap","electroamplified","drummachine","urban","dark"],
    popularityWeek: 0,
    popularityTotal: 0,
    listensTotal: 0,
    downloadsTotal: 0,
    releaseDate: null,
    audioDownloadAllowed: true,
  },
  {
    id: "2242536",
    name: "The Phonk Trap",
    duration: 107,
    artistId: "artist-jack-jack",
    artistName: "Jack Jack",
    albumId: "598446",
    albumName: "",
    audioUrl: "https://prod-1.storage.jamendo.com/?trackid=2242536&format=mp31&from=app-devsite",
    downloadUrl: "https://mp3d.jamendo.com/download/track/2242536/mp32/",
    image: "https://usercontent.jamendo.com/?type=album&id=598446&width=300&trackid=2242536",
    imageSmall: "https://usercontent.jamendo.com/?type=album&id=598446&width=300&trackid=2242536",
    licenseName: null,
    genre: "trap",
    bpm: null,
    speed: null,
    vocalInstrumental: null,
    tags: ["trap","synthesizer","urban","dark"],
    popularityWeek: 0,
    popularityTotal: 0,
    listensTotal: 0,
    downloadsTotal: 0,
    releaseDate: null,
    audioDownloadAllowed: true,
  },
  {
    id: "2165223",
    name: "Dark Action Sports Beat",
    duration: 107,
    artistId: "artist-mokkamusic",
    artistName: "MokkaMusic",
    albumId: "",
    albumName: "",
    audioUrl: "https://prod-1.storage.jamendo.com/?trackid=2165223&format=mp31&from=app-devsite",
    downloadUrl: "https://mp3d.jamendo.com/download/track/2165223/mp32/",
    image: "https://upcdn.io/12a1yuy/image/prd/public/sEIluh3Ytu/hdbNt2qCyqrD1YdlPiyoE.png",
    imageSmall: "https://upcdn.io/12a1yuy/image/prd/public/sEIluh3Ytu/hdbNt2qCyqrD1YdlPiyoE.png",
    licenseName: null,
    genre: "trap",
    bpm: null,
    speed: null,
    vocalInstrumental: null,
    tags: ["trap","strings","bass","urban","dark"],
    popularityWeek: 0,
    popularityTotal: 0,
    listensTotal: 0,
    downloadsTotal: 0,
    releaseDate: null,
    audioDownloadAllowed: true,
  },
  {
    id: "2232402",
    name: "Trap Phonk Energy Drill",
    duration: 105,
    artistId: "artist-alexzavesa",
    artistName: "AlexZavesa",
    albumId: "",
    albumName: "",
    audioUrl: "https://prod-1.storage.jamendo.com/?trackid=2232402&format=mp31&from=app-devsite",
    downloadUrl: "https://mp3d.jamendo.com/download/track/2232402/mp32/",
    image: "https://upcdn.io/12a1yuy/image/prd/public/2hWaEWcICJ/u50aRmUNMYwruOr7nYbEo.png",
    imageSmall: "https://upcdn.io/12a1yuy/image/prd/public/2hWaEWcICJ/u50aRmUNMYwruOr7nYbEo.png",
    licenseName: null,
    genre: "trap",
    bpm: null,
    speed: null,
    vocalInstrumental: null,
    tags: ["trap","synthesizer","videogame","dark"],
    popularityWeek: 0,
    popularityTotal: 0,
    listensTotal: 0,
    downloadsTotal: 0,
    releaseDate: null,
    audioDownloadAllowed: true,
  },
  {
    id: "2232404",
    name: "Trap Phonk Energy Drill",
    duration: 105,
    artistId: "artist-alexzavesa",
    artistName: "AlexZavesa",
    albumId: "",
    albumName: "",
    audioUrl: "https://prod-1.storage.jamendo.com/?trackid=2232404&format=mp31&from=app-devsite",
    downloadUrl: "https://mp3d.jamendo.com/download/track/2232404/mp32/",
    image: "https://upcdn.io/12a1yuy/image/prd/public/2hWaEWcICJ/7xsBCT1xgeck78BDUs6iR.png",
    imageSmall: "https://upcdn.io/12a1yuy/image/prd/public/2hWaEWcICJ/7xsBCT1xgeck78BDUs6iR.png",
    licenseName: null,
    genre: "trap",
    bpm: null,
    speed: null,
    vocalInstrumental: null,
    tags: ["trap","synthesizer","videogame","dark"],
    popularityWeek: 0,
    popularityTotal: 0,
    listensTotal: 0,
    downloadsTotal: 0,
    releaseDate: null,
    audioDownloadAllowed: true,
  },
  {
    id: "2194556",
    name: "Smells OF Money",
    duration: 104,
    artistId: "artist-nazar-hrushko",
    artistName: "Nazar Hrushko",
    albumId: "",
    albumName: "",
    audioUrl: "https://prod-1.storage.jamendo.com/?trackid=2194556&format=mp31&from=app-devsite",
    downloadUrl: "https://mp3d.jamendo.com/download/track/2194556/mp32/",
    image: "https://upcdn.io/12a1yuy/image/prd/public/D8sKKTqnq1/A4ZhHII7tPu5WkmgPlZr6.png",
    imageSmall: "https://upcdn.io/12a1yuy/image/prd/public/D8sKKTqnq1/A4ZhHII7tPu5WkmgPlZr6.png",
    licenseName: null,
    genre: "trap",
    bpm: null,
    speed: null,
    vocalInstrumental: null,
    tags: ["trap","strings","bass","videogame","neutral","dark"],
    popularityWeek: 0,
    popularityTotal: 0,
    listensTotal: 0,
    downloadsTotal: 0,
    releaseDate: null,
    audioDownloadAllowed: true,
  },
  {
    id: "1823015",
    name: "Trap Dark",
    duration: 97,
    artistId: "artist-alexzavesa",
    artistName: "AlexZavesa",
    albumId: "439215",
    albumName: "",
    audioUrl: "https://prod-1.storage.jamendo.com/?trackid=1823015&format=mp31&from=app-devsite",
    downloadUrl: "https://mp3d.jamendo.com/download/track/1823015/mp32/",
    image: "https://usercontent.jamendo.com/?type=album&id=439215&width=300&trackid=1823015",
    imageSmall: "https://usercontent.jamendo.com/?type=album&id=439215&width=300&trackid=1823015",
    licenseName: null,
    genre: "trap",
    bpm: 103,
    speed: null,
    vocalInstrumental: null,
    tags: ["trap","synthesizer","sport","dark","angry"],
    popularityWeek: 0,
    popularityTotal: 0,
    listensTotal: 0,
    downloadsTotal: 0,
    releaseDate: null,
    audioDownloadAllowed: true,
  },
  {
    id: "2228792",
    name: "Football Skills",
    duration: 96,
    artistId: "artist-soulprodmusic",
    artistName: "SoulProdMusic",
    albumId: "591716",
    albumName: "",
    audioUrl: "https://prod-1.storage.jamendo.com/?trackid=2228792&format=mp31&from=app-devsite",
    downloadUrl: "https://mp3d.jamendo.com/download/track/2228792/mp32/",
    image: "https://usercontent.jamendo.com/?type=album&id=591716&width=300&trackid=2228792",
    imageSmall: "https://usercontent.jamendo.com/?type=album&id=591716&width=300&trackid=2228792",
    licenseName: null,
    genre: "trap",
    bpm: null,
    speed: null,
    vocalInstrumental: null,
    tags: ["trap","groovy","aggressive"],
    popularityWeek: 0,
    popularityTotal: 0,
    listensTotal: 0,
    downloadsTotal: 0,
    releaseDate: null,
    audioDownloadAllowed: true,
  },
  {
    id: "2321085",
    name: "CALVARY THREE",
    duration: 73,
    artistId: "artist-kanel-holy",
    artistName: "kanel holy",
    albumId: "",
    albumName: "",
    audioUrl: "https://prod-1.storage.jamendo.com/?trackid=2321085&format=mp31&from=app-devsite",
    downloadUrl: "https://mp3d.jamendo.com/download/track/2321085/mp32/",
    image: "https://upcdn.io/12a1yuy/image/prd/public/WL6p63MceM/kYzH74eSNc1qVbr5D3zif.png",
    imageSmall: "https://upcdn.io/12a1yuy/image/prd/public/WL6p63MceM/kYzH74eSNc1qVbr5D3zif.png",
    licenseName: null,
    genre: "trap",
    bpm: null,
    speed: null,
    vocalInstrumental: null,
    tags: ["trap","strings","piano","bass","urban","neutral","dark","energetic"],
    popularityWeek: 0,
    popularityTotal: 0,
    listensTotal: 0,
    downloadsTotal: 0,
    releaseDate: null,
    audioDownloadAllowed: true,
  },
  {
    id: "1921865",
    name: "Food For Thought",
    duration: 71,
    artistId: "artist-infraction",
    artistName: "Infraction",
    albumId: "",
    albumName: "",
    audioUrl: "https://prod-1.storage.jamendo.com/?trackid=1921865&format=mp31&from=app-devsite",
    downloadUrl: "https://mp3d.jamendo.com/download/track/1921865/mp32/",
    image: "https://upcdn.io/12a1yuy/image/prd/public/QqutgONqMa/mSNnJojlGltcqcR6VMCpP.png",
    imageSmall: "https://upcdn.io/12a1yuy/image/prd/public/QqutgONqMa/mSNnJojlGltcqcR6VMCpP.png",
    licenseName: null,
    genre: "trap",
    bpm: 86,
    speed: null,
    vocalInstrumental: null,
    tags: ["trap","percussion","bass","urban","happy","quirky","angry"],
    popularityWeek: 0,
    popularityTotal: 0,
    listensTotal: 0,
    downloadsTotal: 0,
    releaseDate: null,
    audioDownloadAllowed: true,
  },
  {
    id: "2210558",
    name: "Graveyard Hustle - Spooky Halloween Trap Hip Hop",
    duration: 70,
    artistId: "artist-berool",
    artistName: "Berool",
    albumId: "",
    albumName: "",
    audioUrl: "https://prod-1.storage.jamendo.com/?trackid=2210558&format=mp31&from=app-devsite",
    downloadUrl: "https://mp3d.jamendo.com/download/track/2210558/mp32/",
    image: "https://upcdn.io/12a1yuy/image/prd/public/2AUJBfTgIf/NhIxbRLtyul49Fu8vgeeS.png",
    imageSmall: "https://upcdn.io/12a1yuy/image/prd/public/2AUJBfTgIf/NhIxbRLtyul49Fu8vgeeS.png",
    licenseName: null,
    genre: "trap",
    bpm: null,
    speed: null,
    vocalInstrumental: null,
    tags: ["trap","electroamplified","theremin","halloween","dark"],
    popularityWeek: 0,
    popularityTotal: 0,
    listensTotal: 0,
    downloadsTotal: 0,
    releaseDate: null,
    audioDownloadAllowed: true,
  },
  {
    id: "2304869",
    name: "Won't You Hear Me",
    duration: 359,
    artistId: "artist-elle-indigo",
    artistName: "Elle Indigo",
    albumId: "",
    albumName: "",
    audioUrl: "https://prod-1.storage.jamendo.com/?trackid=2304869&format=mp31&from=app-devsite",
    downloadUrl: "https://mp3d.jamendo.com/download/track/2304869/mp32/",
    image: "https://upcdn.io/12a1yuy/image/prd/public/FXOcayQ73N/mPrnv2Z36dbwqdrhxJzrS.png",
    imageSmall: "https://upcdn.io/12a1yuy/image/prd/public/FXOcayQ73N/mPrnv2Z36dbwqdrhxJzrS.png",
    licenseName: null,
    genre: "alternative",
    bpm: null,
    speed: null,
    vocalInstrumental: null,
    tags: ["alternative","inspirational","introspective"],
    popularityWeek: 0,
    popularityTotal: 0,
    listensTotal: 0,
    downloadsTotal: 0,
    releaseDate: null,
    audioDownloadAllowed: true,
  },
  {
    id: "2248374",
    name: "Move That",
    duration: 307,
    artistId: "artist-cephas",
    artistName: "Cephas",
    albumId: "",
    albumName: "",
    audioUrl: "https://prod-1.storage.jamendo.com/?trackid=2248374&format=mp31&from=app-devsite",
    downloadUrl: "https://mp3d.jamendo.com/download/track/2248374/mp32/",
    image: "https://upcdn.io/12a1yuy/image/prd/public/IAz3lJNRVF/YQDny2doxMcLYDWjfZCXi.png",
    imageSmall: "https://upcdn.io/12a1yuy/image/prd/public/IAz3lJNRVF/YQDny2doxMcLYDWjfZCXi.png",
    licenseName: null,
    genre: "electronic/house",
    bpm: null,
    speed: null,
    vocalInstrumental: null,
    tags: ["electronic/house","strings","bass","clubbing","groovy","energetic"],
    popularityWeek: 0,
    popularityTotal: 0,
    listensTotal: 0,
    downloadsTotal: 0,
    releaseDate: null,
    audioDownloadAllowed: true,
  },
  {
    id: "2280074",
    name: "Reborn",
    duration: 297,
    artistId: "artist-igor-pumphonia",
    artistName: "Igor Pumphonia",
    albumId: "",
    albumName: "",
    audioUrl: "https://prod-1.storage.jamendo.com/?trackid=2280074&format=mp31&from=app-devsite",
    downloadUrl: "https://mp3d.jamendo.com/download/track/2280074/mp32/",
    image: "https://upcdn.io/12a1yuy/image/prd/public/Zy0wh4Ttbw/zdvZNSioQInm5EMjRqlPX.png",
    imageSmall: "https://upcdn.io/12a1yuy/image/prd/public/Zy0wh4Ttbw/zdvZNSioQInm5EMjRqlPX.png",
    licenseName: null,
    genre: "electronic",
    bpm: null,
    speed: null,
    vocalInstrumental: null,
    tags: ["electronic","synthesizer","fashion","emotional","neutral","motivational","inspirational"],
    popularityWeek: 0,
    popularityTotal: 0,
    listensTotal: 0,
    downloadsTotal: 0,
    releaseDate: null,
    audioDownloadAllowed: true,
  },
  {
    id: "2206319",
    name: "Tech House Music",
    duration: 252,
    artistId: "artist-yurasoop",
    artistName: "YuraSoop",
    albumId: "",
    albumName: "",
    audioUrl: "https://prod-1.storage.jamendo.com/?trackid=2206319&format=mp31&from=app-devsite",
    downloadUrl: "https://mp3d.jamendo.com/download/track/2206319/mp32/",
    image: "https://upcdn.io/12a1yuy/image/prd/public/RPiAnrFmHL/juxQneGdRDklnyFembAmi.png",
    imageSmall: "https://upcdn.io/12a1yuy/image/prd/public/RPiAnrFmHL/juxQneGdRDklnyFembAmi.png",
    licenseName: null,
    genre: "electronic/house",
    bpm: null,
    speed: null,
    vocalInstrumental: null,
    tags: ["electronic/house","strings","bass","party","happy","energetic"],
    popularityWeek: 0,
    popularityTotal: 0,
    listensTotal: 0,
    downloadsTotal: 0,
    releaseDate: null,
    audioDownloadAllowed: true,
  },
  {
    id: "2326786",
    name: "GIIX",
    duration: 240,
    artistId: "artist-gallium",
    artistName: "Gallium",
    albumId: "",
    albumName: "",
    audioUrl: "https://prod-1.storage.jamendo.com/?trackid=2326786&format=mp31&from=app-devsite",
    downloadUrl: "https://mp3d.jamendo.com/download/track/2326786/mp32/",
    image: "https://upcdn.io/12a1yuy/image/prd/public/OtKzQdUycR/YJt9B7ShUEX4kuQE3YnHQ.png",
    imageSmall: "https://upcdn.io/12a1yuy/image/prd/public/OtKzQdUycR/YJt9B7ShUEX4kuQE3YnHQ.png",
    licenseName: null,
    genre: "experimental",
    bpm: null,
    speed: null,
    vocalInstrumental: null,
    tags: ["experimental","guitar","electroamplified","drummachine","hybrid","dark","sad"],
    popularityWeek: 0,
    popularityTotal: 0,
    listensTotal: 0,
    downloadsTotal: 0,
    releaseDate: null,
    audioDownloadAllowed: true,
  },
  {
    id: "2163416",
    name: "UK Bassline Bass House",
    duration: 225,
    artistId: "artist-mokkamusic",
    artistName: "MokkaMusic",
    albumId: "",
    albumName: "",
    audioUrl: "https://prod-1.storage.jamendo.com/?trackid=2163416&format=mp31&from=app-devsite",
    downloadUrl: "https://mp3d.jamendo.com/download/track/2163416/mp32/",
    image: "https://upcdn.io/12a1yuy/image/prd/public/sEIluh3Ytu/qDPrFrnTbgRJxhAt2FwQo.png",
    imageSmall: "https://upcdn.io/12a1yuy/image/prd/public/sEIluh3Ytu/qDPrFrnTbgRJxhAt2FwQo.png",
    licenseName: null,
    genre: "electronic/house",
    bpm: null,
    speed: null,
    vocalInstrumental: null,
    tags: ["electronic/house","electroamplified","drummachine","clubbing","dark","upbeat"],
    popularityWeek: 0,
    popularityTotal: 0,
    listensTotal: 0,
    downloadsTotal: 0,
    releaseDate: null,
    audioDownloadAllowed: true,
  },
  {
    id: "1963752",
    name: "Trap Phonk Background Music Black Market in China",
    duration: 222,
    artistId: "artist-timofiy-starenkov",
    artistName: "Timofiy Starenkov",
    albumId: "",
    albumName: "",
    audioUrl: "https://prod-1.storage.jamendo.com/?trackid=1963752&format=mp31&from=app-devsite",
    downloadUrl: "https://mp3d.jamendo.com/download/track/1963752/mp32/",
    image: "https://upcdn.io/12a1yuy/image/prd/public/G9k6XP3gIN/PdGjKlsPA5uDoP8xAln8L.png",
    imageSmall: "https://upcdn.io/12a1yuy/image/prd/public/G9k6XP3gIN/PdGjKlsPA5uDoP8xAln8L.png",
    licenseName: null,
    genre: "world/asian/central asia",
    bpm: 140,
    speed: null,
    vocalInstrumental: null,
    tags: ["world/asian/central asia","synthesizer","koto","ethno","neutral","powerful"],
    popularityWeek: 0,
    popularityTotal: 0,
    listensTotal: 0,
    downloadsTotal: 0,
    releaseDate: null,
    audioDownloadAllowed: true,
  },
  {
    id: "1371989",
    name: "Oriental Music Library HB2002",
    duration: 218,
    artistId: "artist-hitomi-lai",
    artistName: "Hitomi Lai",
    albumId: "",
    albumName: "",
    audioUrl: "https://prod-1.storage.jamendo.com/?trackid=1371989&format=mp31&from=app-devsite",
    downloadUrl: "https://mp3d.jamendo.com/download/track/1371989/mp32/",
    image: "https://upcdn.io/12a1yuy/image/prd/public/3IILxg0y19/xNecsTpD04LOp7aOz6vbu.png",
    imageSmall: "https://upcdn.io/12a1yuy/image/prd/public/3IILxg0y19/xNecsTpD04LOp7aOz6vbu.png",
    licenseName: null,
    genre: "world/asian/central asia",
    bpm: 146,
    speed: null,
    vocalInstrumental: null,
    tags: ["world/asian/central asia","koto","soft","neutral"],
    popularityWeek: 0,
    popularityTotal: 0,
    listensTotal: 0,
    downloadsTotal: 0,
    releaseDate: null,
    audioDownloadAllowed: true,
  },
  {
    id: "2040212",
    name: "Frank, the Lady, and the Pier",
    duration: 216,
    artistId: "artist-l-m-w",
    artistName: "L.M.W.",
    albumId: "",
    albumName: "",
    audioUrl: "https://prod-1.storage.jamendo.com/?trackid=2040212&format=mp31&from=app-devsite",
    downloadUrl: "https://mp3d.jamendo.com/download/track/2040212/mp32/",
    image: "https://upcdn.io/12a1yuy/image/prd/public/oQBs28ryME/vyDJ4cf4mvH0935QAzx73.png",
    imageSmall: "https://upcdn.io/12a1yuy/image/prd/public/oQBs28ryME/vyDJ4cf4mvH0935QAzx73.png",
    licenseName: null,
    genre: "alternative",
    bpm: 100,
    speed: null,
    vocalInstrumental: null,
    tags: ["alternative","classicalguitar","drummachine","drama","neutral"],
    popularityWeek: 0,
    popularityTotal: 0,
    listensTotal: 0,
    downloadsTotal: 0,
    releaseDate: null,
    audioDownloadAllowed: true,
  },
  {
    id: "2326296",
    name: "Gangster",
    duration: 212,
    artistId: "artist-yurasoop",
    artistName: "YuraSoop",
    albumId: "",
    albumName: "",
    audioUrl: "https://prod-1.storage.jamendo.com/?trackid=2326296&format=mp31&from=app-devsite",
    downloadUrl: "https://mp3d.jamendo.com/download/track/2326296/mp32/",
    image: "https://upcdn.io/12a1yuy/image/prd/public/RPiAnrFmHL/aPMC8lJXHiQa7irwbjQcC.png",
    imageSmall: "https://upcdn.io/12a1yuy/image/prd/public/RPiAnrFmHL/aPMC8lJXHiQa7irwbjQcC.png",
    licenseName: null,
    genre: "phonk",
    bpm: null,
    speed: null,
    vocalInstrumental: null,
    tags: ["hip-hop/rap","strings","bass","urban","dark","sad"],
    popularityWeek: 0,
    popularityTotal: 0,
    listensTotal: 0,
    downloadsTotal: 0,
    releaseDate: null,
    audioDownloadAllowed: true,
  },
  {
    id: "2272796",
    name: "wounds of time",
    duration: 208,
    artistId: "artist-raeth",
    artistName: "Øraeth",
    albumId: "",
    albumName: "",
    audioUrl: "https://prod-1.storage.jamendo.com/?trackid=2272796&format=mp31&from=app-devsite",
    downloadUrl: "https://mp3d.jamendo.com/download/track/2272796/mp32/",
    image: "https://upcdn.io/12a1yuy/image/prd/public/QZ4hGpQCGJ/5dIcp2pCgM4qGe9x6iG7s.png",
    imageSmall: "https://upcdn.io/12a1yuy/image/prd/public/QZ4hGpQCGJ/5dIcp2pCgM4qGe9x6iG7s.png",
    licenseName: null,
    genre: "electronic",
    bpm: null,
    speed: null,
    vocalInstrumental: null,
    tags: ["electronic","synthesizer","atmospheric","emotional"],
    popularityWeek: 0,
    popularityTotal: 0,
    listensTotal: 0,
    downloadsTotal: 0,
    releaseDate: null,
    audioDownloadAllowed: true,
  },
  {
    id: "1371998",
    name: "Oriental Music Library HB2011",
    duration: 186,
    artistId: "artist-hitomi-lai",
    artistName: "Hitomi Lai",
    albumId: "",
    albumName: "",
    audioUrl: "https://prod-1.storage.jamendo.com/?trackid=1371998&format=mp31&from=app-devsite",
    downloadUrl: "https://mp3d.jamendo.com/download/track/1371998/mp32/",
    image: "https://upcdn.io/12a1yuy/image/prd/public/3IILxg0y19/zL82f7zEQ111jwq7P1976.png",
    imageSmall: "https://upcdn.io/12a1yuy/image/prd/public/3IILxg0y19/zL82f7zEQ111jwq7P1976.png",
    licenseName: null,
    genre: "world/asian/central asia",
    bpm: 120,
    speed: null,
    vocalInstrumental: null,
    tags: ["world/asian/central asia","koto","neutral","groovy"],
    popularityWeek: 0,
    popularityTotal: 0,
    listensTotal: 0,
    downloadsTotal: 0,
    releaseDate: null,
    audioDownloadAllowed: true,
  },
  {
    id: "2310522",
    name: "Foggy Morning",
    duration: 180,
    artistId: "artist-macroform",
    artistName: "Macroform",
    albumId: "",
    albumName: "",
    audioUrl: "https://prod-1.storage.jamendo.com/?trackid=2310522&format=mp31&from=app-devsite",
    downloadUrl: "https://mp3d.jamendo.com/download/track/2310522/mp32/",
    image: "https://upcdn.io/12a1yuy/image/prd/public/AlXlQRok9q/rK9W1rUwPx12m0bzQc3bx.png",
    imageSmall: "https://upcdn.io/12a1yuy/image/prd/public/AlXlQRok9q/rK9W1rUwPx12m0bzQc3bx.png",
    licenseName: null,
    genre: "alternative",
    bpm: null,
    speed: null,
    vocalInstrumental: null,
    tags: ["alternative","guitar","strings","hybrid","happy","calm","cheerful"],
    popularityWeek: 0,
    popularityTotal: 0,
    listensTotal: 0,
    downloadsTotal: 0,
    releaseDate: null,
    audioDownloadAllowed: true,
  },
  {
    id: "2231895",
    name: "GanGster brother",
    duration: 177,
    artistId: "artist-vzen-instrumental-beat",
    artistName: "Vzen instrumental beat",
    albumId: "",
    albumName: "",
    audioUrl: "https://prod-1.storage.jamendo.com/?trackid=2231895&format=mp31&from=app-devsite",
    downloadUrl: "https://mp3d.jamendo.com/download/track/2231895/mp32/",
    image: "https://upcdn.io/12a1yuy/image/prd/public/jUChFOWssi/k9G5tcZcDZ4pvbvudyyml.png",
    imageSmall: "https://upcdn.io/12a1yuy/image/prd/public/jUChFOWssi/k9G5tcZcDZ4pvbvudyyml.png",
    licenseName: null,
    genre: "phonk",
    bpm: null,
    speed: null,
    vocalInstrumental: null,
    tags: ["hip-hop/rap","synthesizer","scifi","neutral","scary","aggressive"],
    popularityWeek: 0,
    popularityTotal: 0,
    listensTotal: 0,
    downloadsTotal: 0,
    releaseDate: null,
    audioDownloadAllowed: true,
  },
  {
    id: "1939856",
    name: "Imagawa Yoshimoto no daraku",
    duration: 176,
    artistId: "artist-david-chas",
    artistName: "David Chas",
    albumId: "",
    albumName: "",
    audioUrl: "https://prod-1.storage.jamendo.com/?trackid=1939856&format=mp31&from=app-devsite",
    downloadUrl: "https://mp3d.jamendo.com/download/track/1939856/mp32/",
    image: "https://upcdn.io/12a1yuy/image/prd/public/MgtcJeS1Qf/OGXpuGMkl16MoE6esUpx7.png",
    imageSmall: "https://upcdn.io/12a1yuy/image/prd/public/MgtcJeS1Qf/OGXpuGMkl16MoE6esUpx7.png",
    licenseName: null,
    genre: "world/asian/central asia",
    bpm: 130,
    speed: null,
    vocalInstrumental: null,
    tags: ["world/asian/central asia","percussion","koto","action","neutral","dramatic"],
    popularityWeek: 0,
    popularityTotal: 0,
    listensTotal: 0,
    downloadsTotal: 0,
    releaseDate: null,
    audioDownloadAllowed: true,
  },
  {
    id: "2327346",
    name: "Contemplation",
    duration: 175,
    artistId: "artist-macroform",
    artistName: "Macroform",
    albumId: "",
    albumName: "",
    audioUrl: "https://prod-1.storage.jamendo.com/?trackid=2327346&format=mp31&from=app-devsite",
    downloadUrl: "https://mp3d.jamendo.com/download/track/2327346/mp32/",
    image: "https://upcdn.io/12a1yuy/image/prd/public/AlXlQRok9q/PGGBlTWnXlgeg9SFtoYdw.png",
    imageSmall: "https://upcdn.io/12a1yuy/image/prd/public/AlXlQRok9q/PGGBlTWnXlgeg9SFtoYdw.png",
    licenseName: null,
    genre: "alternative",
    bpm: null,
    speed: null,
    vocalInstrumental: null,
    tags: ["alternative","drums","electricguitar","electroamplified","hybrid","neutral","calm"],
    popularityWeek: 0,
    popularityTotal: 0,
    listensTotal: 0,
    downloadsTotal: 0,
    releaseDate: null,
    audioDownloadAllowed: true,
  },
  {
    id: "2238843",
    name: "Reverie | Hiphop Music",
    duration: 172,
    artistId: "artist-praz-khanal",
    artistName: "Praz Khanal",
    albumId: "596614",
    albumName: "",
    audioUrl: "https://prod-1.storage.jamendo.com/?trackid=2238843&format=mp31&from=app-devsite",
    downloadUrl: "https://mp3d.jamendo.com/download/track/2238843/mp32/",
    image: "https://usercontent.jamendo.com/?type=album&id=596614&width=300&trackid=2238843",
    imageSmall: "https://usercontent.jamendo.com/?type=album&id=596614&width=300&trackid=2238843",
    licenseName: null,
    genre: "phonk",
    bpm: null,
    speed: null,
    vocalInstrumental: null,
    tags: ["hip-hop/rap","percussion","bass","cymbal","urban","dark"],
    popularityWeek: 0,
    popularityTotal: 0,
    listensTotal: 0,
    downloadsTotal: 0,
    releaseDate: null,
    audioDownloadAllowed: true,
  },
  {
    id: "2252004",
    name: "Дао вечерних улиц",
    duration: 172,
    artistId: "artist-surmachina",
    artistName: "Surmachina",
    albumId: "",
    albumName: "",
    audioUrl: "https://prod-1.storage.jamendo.com/?trackid=2252004&format=mp31&from=app-devsite",
    downloadUrl: "https://mp3d.jamendo.com/download/track/2252004/mp32/",
    image: "https://upcdn.io/12a1yuy/image/prd/public/vFDwhDEiv4/mMEYd4sj61Zr2ov9RPg81.png",
    imageSmall: "https://upcdn.io/12a1yuy/image/prd/public/vFDwhDEiv4/mMEYd4sj61Zr2ov9RPg81.png",
    licenseName: null,
    genre: "phonk",
    bpm: null,
    speed: null,
    vocalInstrumental: null,
    tags: ["hip-hop/rap","strings","bass","urban","neutral","dark"],
    popularityWeek: 0,
    popularityTotal: 0,
    listensTotal: 0,
    downloadsTotal: 0,
    releaseDate: null,
    audioDownloadAllowed: true,
  },
  {
    id: "1725148",
    name: "Creative Glitch Timelapse",
    duration: 168,
    artistId: "artist-yevhen-lokhmatov",
    artistName: "Yevhen Lokhmatov",
    albumId: "",
    albumName: "",
    audioUrl: "https://prod-1.storage.jamendo.com/?trackid=1725148&format=mp31&from=app-devsite",
    downloadUrl: "https://mp3d.jamendo.com/download/track/1725148/mp32/",
    image: "https://upcdn.io/12a1yuy/image/prd/public/kQxkePXOKR/HCc5gySh6zVSzShKX362N.png",
    imageSmall: "https://upcdn.io/12a1yuy/image/prd/public/kQxkePXOKR/HCc5gySh6zVSzShKX362N.png",
    licenseName: null,
    genre: "electronic",
    bpm: 140,
    speed: null,
    vocalInstrumental: null,
    tags: ["electronic","synthesizer","bass","abstract","technology","emotional","neutral"],
    popularityWeek: 0,
    popularityTotal: 0,
    listensTotal: 0,
    downloadsTotal: 0,
    releaseDate: null,
    audioDownloadAllowed: true,
  },
  {
    id: "2268792",
    name: "Fashion Summer Uplifting Lounge House",
    duration: 168,
    artistId: "artist-art-media",
    artistName: "Art Media",
    albumId: "",
    albumName: "",
    audioUrl: "https://prod-1.storage.jamendo.com/?trackid=2268792&format=mp31&from=app-devsite",
    downloadUrl: "https://mp3d.jamendo.com/download/track/2268792/mp32/",
    image: "https://upcdn.io/12a1yuy/image/prd/public/6xRUNH9qn2/tHCpMQQ2r396dOFou6OUG.png",
    imageSmall: "https://upcdn.io/12a1yuy/image/prd/public/6xRUNH9qn2/tHCpMQQ2r396dOFou6OUG.png",
    licenseName: null,
    genre: "electronic/house",
    bpm: null,
    speed: null,
    vocalInstrumental: null,
    tags: ["electronic/house","guitar","strings","bass","celebration","happy","energetic"],
    popularityWeek: 0,
    popularityTotal: 0,
    listensTotal: 0,
    downloadsTotal: 0,
    releaseDate: null,
    audioDownloadAllowed: true,
  },
  {
    id: "1372008",
    name: "Oriental Music Library HB2020",
    duration: 160,
    artistId: "artist-hitomi-lai",
    artistName: "Hitomi Lai",
    albumId: "",
    albumName: "",
    audioUrl: "https://prod-1.storage.jamendo.com/?trackid=1372008&format=mp31&from=app-devsite",
    downloadUrl: "https://mp3d.jamendo.com/download/track/1372008/mp32/",
    image: "https://upcdn.io/12a1yuy/image/prd/public/3IILxg0y19/9OD3HILz1rAqqeT7raHUX.png",
    imageSmall: "https://upcdn.io/12a1yuy/image/prd/public/3IILxg0y19/9OD3HILz1rAqqeT7raHUX.png",
    licenseName: null,
    genre: "world/asian/central asia",
    bpm: 100,
    speed: null,
    vocalInstrumental: null,
    tags: ["world/asian/central asia","koto","soft","neutral"],
    popularityWeek: 0,
    popularityTotal: 0,
    listensTotal: 0,
    downloadsTotal: 0,
    releaseDate: null,
    audioDownloadAllowed: true,
  },
  {
    id: "2264053",
    name: "Coronavirus Kills",
    duration: 158,
    artistId: "artist-yurasoop",
    artistName: "YuraSoop",
    albumId: "",
    albumName: "",
    audioUrl: "https://prod-1.storage.jamendo.com/?trackid=2264053&format=mp31&from=app-devsite",
    downloadUrl: "https://mp3d.jamendo.com/download/track/2264053/mp32/",
    image: "https://upcdn.io/12a1yuy/image/prd/public/RPiAnrFmHL/Ca2jX0Aym86bszkLcUrn3.png",
    imageSmall: "https://upcdn.io/12a1yuy/image/prd/public/RPiAnrFmHL/Ca2jX0Aym86bszkLcUrn3.png",
    licenseName: null,
    genre: "electronic/dubstep/grime",
    bpm: null,
    speed: null,
    vocalInstrumental: null,
    tags: ["electronic/dubstep/grime","drums","bass","urban","energetic","angry"],
    popularityWeek: 0,
    popularityTotal: 0,
    listensTotal: 0,
    downloadsTotal: 0,
    releaseDate: null,
    audioDownloadAllowed: true,
  },
  {
    id: "2311680",
    name: "Run Free",
    duration: 156,
    artistId: "artist-whitecat",
    artistName: "WhiteCat",
    albumId: "",
    albumName: "",
    audioUrl: "https://prod-1.storage.jamendo.com/?trackid=2311680&format=mp31&from=app-devsite",
    downloadUrl: "https://mp3d.jamendo.com/download/track/2311680/mp32/",
    image: "https://upcdn.io/12a1yuy/image/prd/public/qAWCsaXsvY/IIEZVYSlvmeCq6rDtX9SV.png",
    imageSmall: "https://upcdn.io/12a1yuy/image/prd/public/qAWCsaXsvY/IIEZVYSlvmeCq6rDtX9SV.png",
    licenseName: null,
    genre: "alternative",
    bpm: null,
    speed: null,
    vocalInstrumental: null,
    tags: ["alternative","happy","energetic"],
    popularityWeek: 0,
    popularityTotal: 0,
    listensTotal: 0,
    downloadsTotal: 0,
    releaseDate: null,
    audioDownloadAllowed: true,
  },
  {
    id: "2298494",
    name: "Drill Beat",
    duration: 155,
    artistId: "artist-yurasoop",
    artistName: "YuraSoop",
    albumId: "",
    albumName: "",
    audioUrl: "https://prod-1.storage.jamendo.com/?trackid=2298494&format=mp31&from=app-devsite",
    downloadUrl: "https://mp3d.jamendo.com/download/track/2298494/mp32/",
    image: "https://upcdn.io/12a1yuy/image/prd/public/RPiAnrFmHL/e7TNvPiPFl0ZIi9VxuJ8w.png",
    imageSmall: "https://upcdn.io/12a1yuy/image/prd/public/RPiAnrFmHL/e7TNvPiPFl0ZIi9VxuJ8w.png",
    licenseName: null,
    genre: "phonk",
    bpm: null,
    speed: null,
    vocalInstrumental: null,
    tags: ["hip-hop/rap","strings","bass","urban","neutral","energetic","aggressive"],
    popularityWeek: 0,
    popularityTotal: 0,
    listensTotal: 0,
    downloadsTotal: 0,
    releaseDate: null,
    audioDownloadAllowed: true,
  },
  {
    id: "2284964",
    name: "Cyber House",
    duration: 150,
    artistId: "artist-alexey-anisimov",
    artistName: "Alexey Anisimov",
    albumId: "",
    albumName: "",
    audioUrl: "https://prod-1.storage.jamendo.com/?trackid=2284964&format=mp31&from=app-devsite",
    downloadUrl: "https://mp3d.jamendo.com/download/track/2284964/mp32/",
    image: "https://upcdn.io/12a1yuy/image/prd/public/3BRrkHUW8X/DGB0SKbfk6SOk6b1a6UPB.png",
    imageSmall: "https://upcdn.io/12a1yuy/image/prd/public/3BRrkHUW8X/DGB0SKbfk6SOk6b1a6UPB.png",
    licenseName: null,
    genre: "electronic/electro house",
    bpm: null,
    speed: null,
    vocalInstrumental: null,
    tags: ["electronic/electro house","synthesizer","sport","neutral","powerful","angry"],
    popularityWeek: 0,
    popularityTotal: 0,
    listensTotal: 0,
    downloadsTotal: 0,
    releaseDate: null,
    audioDownloadAllowed: true,
  },
  {
    id: "2165225",
    name: "Retrosynth Cinematic Space Trailer",
    duration: 145,
    artistId: "artist-mokkamusic",
    artistName: "MokkaMusic",
    albumId: "",
    albumName: "",
    audioUrl: "https://prod-1.storage.jamendo.com/?trackid=2165225&format=mp31&from=app-devsite",
    downloadUrl: "https://mp3d.jamendo.com/download/track/2165225/mp32/",
    image: "https://upcdn.io/12a1yuy/image/prd/public/sEIluh3Ytu/qFaA7Dlp9M1xtP72irrZf.png",
    imageSmall: "https://upcdn.io/12a1yuy/image/prd/public/sEIluh3Ytu/qFaA7Dlp9M1xtP72irrZf.png",
    licenseName: null,
    genre: "electronic",
    bpm: null,
    speed: null,
    vocalInstrumental: null,
    tags: ["electronic","synthesizer","bass","videogame","emotional"],
    popularityWeek: 0,
    popularityTotal: 0,
    listensTotal: 0,
    downloadsTotal: 0,
    releaseDate: null,
    audioDownloadAllowed: true,
  },
  {
    id: "2157110",
    name: "Cinematic Synthwave Trailer",
    duration: 142,
    artistId: "artist-mokkamusic",
    artistName: "MokkaMusic",
    albumId: "",
    albumName: "",
    audioUrl: "https://prod-1.storage.jamendo.com/?trackid=2157110&format=mp31&from=app-devsite",
    downloadUrl: "https://mp3d.jamendo.com/download/track/2157110/mp32/",
    image: "https://upcdn.io/12a1yuy/image/prd/public/sEIluh3Ytu/piMf5H2Slv3JPZVkKCUjd.png",
    imageSmall: "https://upcdn.io/12a1yuy/image/prd/public/sEIluh3Ytu/piMf5H2Slv3JPZVkKCUjd.png",
    licenseName: null,
    genre: "electronic",
    bpm: null,
    speed: null,
    vocalInstrumental: null,
    tags: ["electronic","synthesizer","bass","retro","emotional"],
    popularityWeek: 0,
    popularityTotal: 0,
    listensTotal: 0,
    downloadsTotal: 0,
    releaseDate: null,
    audioDownloadAllowed: true,
  },
  {
    id: "2149892",
    name: "Bass House Phonk",
    duration: 139,
    artistId: "artist-mokkamusic",
    artistName: "MokkaMusic",
    albumId: "",
    albumName: "",
    audioUrl: "https://prod-1.storage.jamendo.com/?trackid=2149892&format=mp31&from=app-devsite",
    downloadUrl: "https://mp3d.jamendo.com/download/track/2149892/mp32/",
    image: "https://upcdn.io/12a1yuy/image/prd/public/sEIluh3Ytu/XnSaz2RXJXiMFrSnlYtGX.png",
    imageSmall: "https://upcdn.io/12a1yuy/image/prd/public/sEIluh3Ytu/XnSaz2RXJXiMFrSnlYtGX.png",
    licenseName: null,
    genre: "electronic/house",
    bpm: null,
    speed: null,
    vocalInstrumental: null,
    tags: ["electronic/house","cowbell","videogame","dark","energetic"],
    popularityWeek: 0,
    popularityTotal: 0,
    listensTotal: 0,
    downloadsTotal: 0,
    releaseDate: null,
    audioDownloadAllowed: true,
  },
  {
    id: "2299099",
    name: "Razor (Dark Glitch Electronic DnB)",
    duration: 138,
    artistId: "artist-databend",
    artistName: "Databend",
    albumId: "",
    albumName: "",
    audioUrl: "https://prod-1.storage.jamendo.com/?trackid=2299099&format=mp31&from=app-devsite",
    downloadUrl: "https://mp3d.jamendo.com/download/track/2299099/mp32/",
    image: "https://upcdn.io/12a1yuy/image/prd/public/s4nBIfQjNi/vnDofSG8anjeExGRMcyZ9.png",
    imageSmall: "https://upcdn.io/12a1yuy/image/prd/public/s4nBIfQjNi/vnDofSG8anjeExGRMcyZ9.png",
    licenseName: null,
    genre: "electronic/drum & bass",
    bpm: null,
    speed: null,
    vocalInstrumental: null,
    tags: ["electronic/drum & bass","synthesizer","drummachine","technology","neutral","dark"],
    popularityWeek: 0,
    popularityTotal: 0,
    listensTotal: 0,
    downloadsTotal: 0,
    releaseDate: null,
    audioDownloadAllowed: true,
  },
  {
    id: "2163400",
    name: "Synthwave Soundtrack",
    duration: 136,
    artistId: "artist-mokkamusic",
    artistName: "MokkaMusic",
    albumId: "",
    albumName: "",
    audioUrl: "https://prod-1.storage.jamendo.com/?trackid=2163400&format=mp31&from=app-devsite",
    downloadUrl: "https://mp3d.jamendo.com/download/track/2163400/mp32/",
    image: "https://upcdn.io/12a1yuy/image/prd/public/sEIluh3Ytu/Jv34cAVhWKGUs2lttXEuQ.png",
    imageSmall: "https://upcdn.io/12a1yuy/image/prd/public/sEIluh3Ytu/Jv34cAVhWKGUs2lttXEuQ.png",
    licenseName: null,
    genre: "electronic",
    bpm: null,
    speed: null,
    vocalInstrumental: null,
    tags: ["electronic","synthesizer","scifi","emotional"],
    popularityWeek: 0,
    popularityTotal: 0,
    listensTotal: 0,
    downloadsTotal: 0,
    releaseDate: null,
    audioDownloadAllowed: true,
  },
  {
    id: "2149891",
    name: "Night Drive Phonk",
    duration: 134,
    artistId: "artist-mokkamusic",
    artistName: "MokkaMusic",
    albumId: "",
    albumName: "",
    audioUrl: "https://prod-1.storage.jamendo.com/?trackid=2149891&format=mp31&from=app-devsite",
    downloadUrl: "https://mp3d.jamendo.com/download/track/2149891/mp32/",
    image: "https://upcdn.io/12a1yuy/image/prd/public/sEIluh3Ytu/1E12IE5MytMbR2ILorSSc.png",
    imageSmall: "https://upcdn.io/12a1yuy/image/prd/public/sEIluh3Ytu/1E12IE5MytMbR2ILorSSc.png",
    licenseName: null,
    genre: "electronic/house",
    bpm: null,
    speed: null,
    vocalInstrumental: null,
    tags: ["electronic/house","bass","cowbell","fashion","energetic"],
    popularityWeek: 0,
    popularityTotal: 0,
    listensTotal: 0,
    downloadsTotal: 0,
    releaseDate: null,
    audioDownloadAllowed: true,
  },
  {
    id: "1372001",
    name: "Oriental Music Library HB2013",
    duration: 130,
    artistId: "artist-hitomi-lai",
    artistName: "Hitomi Lai",
    albumId: "",
    albumName: "",
    audioUrl: "https://prod-1.storage.jamendo.com/?trackid=1372001&format=mp31&from=app-devsite",
    downloadUrl: "https://mp3d.jamendo.com/download/track/1372001/mp32/",
    image: "https://upcdn.io/12a1yuy/image/prd/public/3IILxg0y19/Nkb9JMLOJe72zqUCDVAE7.png",
    imageSmall: "https://upcdn.io/12a1yuy/image/prd/public/3IILxg0y19/Nkb9JMLOJe72zqUCDVAE7.png",
    licenseName: null,
    genre: "world/asian/central asia",
    bpm: 106,
    speed: null,
    vocalInstrumental: null,
    tags: ["world/asian/central asia","koto","soft","neutral"],
    popularityWeek: 0,
    popularityTotal: 0,
    listensTotal: 0,
    downloadsTotal: 0,
    releaseDate: null,
    audioDownloadAllowed: true,
  },
  {
    id: "1693295",
    name: "Middle East",
    duration: 127,
    artistId: "artist-future-near-records",
    artistName: "Future Near Records",
    albumId: "",
    albumName: "",
    audioUrl: "https://prod-1.storage.jamendo.com/?trackid=1693295&format=mp31&from=app-devsite",
    downloadUrl: "https://mp3d.jamendo.com/download/track/1693295/mp32/",
    image: "https://upcdn.io/12a1yuy/image/prd/public/1vaf5Vcj15/61AzzfQiz2rKczIqkFnyI.png",
    imageSmall: "https://upcdn.io/12a1yuy/image/prd/public/1vaf5Vcj15/61AzzfQiz2rKczIqkFnyI.png",
    licenseName: null,
    genre: "world/asian/central asia",
    bpm: 107,
    speed: null,
    vocalInstrumental: null,
    tags: ["world/asian/central asia","synthesizer","bongo","neutral","groovy"],
    popularityWeek: 0,
    popularityTotal: 0,
    listensTotal: 0,
    downloadsTotal: 0,
    releaseDate: null,
    audioDownloadAllowed: true,
  },
  {
    id: "2242745",
    name: "Aggressive House",
    duration: 123,
    artistId: "artist-jack-jack",
    artistName: "Jack Jack",
    albumId: "598520",
    albumName: "",
    audioUrl: "https://prod-1.storage.jamendo.com/?trackid=2242745&format=mp31&from=app-devsite",
    downloadUrl: "https://mp3d.jamendo.com/download/track/2242745/mp32/",
    image: "https://usercontent.jamendo.com/?type=album&id=598520&width=300&trackid=2242745",
    imageSmall: "https://usercontent.jamendo.com/?type=album&id=598520&width=300&trackid=2242745",
    licenseName: null,
    genre: "electronic/house",
    bpm: null,
    speed: null,
    vocalInstrumental: null,
    tags: ["electronic/house","synthesizer","sport","angry"],
    popularityWeek: 0,
    popularityTotal: 0,
    listensTotal: 0,
    downloadsTotal: 0,
    releaseDate: null,
    audioDownloadAllowed: true,
  },
  {
    id: "2165233",
    name: "Aggressive Brazilian Phonk",
    duration: 118,
    artistId: "artist-mokkamusic",
    artistName: "MokkaMusic",
    albumId: "",
    albumName: "",
    audioUrl: "https://prod-1.storage.jamendo.com/?trackid=2165233&format=mp31&from=app-devsite",
    downloadUrl: "https://mp3d.jamendo.com/download/track/2165233/mp32/",
    image: "https://upcdn.io/12a1yuy/image/prd/public/sEIluh3Ytu/t9sXhOMBUpNZllrB7Q4DL.png",
    imageSmall: "https://upcdn.io/12a1yuy/image/prd/public/sEIluh3Ytu/t9sXhOMBUpNZllrB7Q4DL.png",
    licenseName: null,
    genre: "phonk",
    bpm: null,
    speed: null,
    vocalInstrumental: null,
    tags: ["hip-hop/rap","bass","drummachine","urban","dark"],
    popularityWeek: 0,
    popularityTotal: 0,
    listensTotal: 0,
    downloadsTotal: 0,
    releaseDate: null,
    audioDownloadAllowed: true,
  },
  {
    id: "2265775",
    name: "New Metal",
    duration: 114,
    artistId: "artist-moanum-music",
    artistName: "Moanum Music",
    albumId: "",
    albumName: "",
    audioUrl: "https://prod-1.storage.jamendo.com/?trackid=2265775&format=mp31&from=app-devsite",
    downloadUrl: "https://mp3d.jamendo.com/download/track/2265775/mp32/",
    image: "https://upcdn.io/12a1yuy/image/prd/public/3KwcldmhXu/cFcz8hW6bmhI44yDV82X3.png",
    imageSmall: "https://upcdn.io/12a1yuy/image/prd/public/3KwcldmhXu/cFcz8hW6bmhI44yDV82X3.png",
    licenseName: null,
    genre: "rock/heavy metal",
    bpm: null,
    speed: null,
    vocalInstrumental: null,
    tags: ["rock/heavy metal","drums","guitar","sport","angry"],
    popularityWeek: 0,
    popularityTotal: 0,
    listensTotal: 0,
    downloadsTotal: 0,
    releaseDate: null,
    audioDownloadAllowed: true,
  },
  {
    id: "2149894",
    name: "Anime Phonk",
    duration: 111,
    artistId: "artist-mokkamusic",
    artistName: "MokkaMusic",
    albumId: "",
    albumName: "",
    audioUrl: "https://prod-1.storage.jamendo.com/?trackid=2149894&format=mp31&from=app-devsite",
    downloadUrl: "https://mp3d.jamendo.com/download/track/2149894/mp32/",
    image: "https://upcdn.io/12a1yuy/image/prd/public/sEIluh3Ytu/01yof9LVEyxt3JmWAjxZL.png",
    imageSmall: "https://upcdn.io/12a1yuy/image/prd/public/sEIluh3Ytu/01yof9LVEyxt3JmWAjxZL.png",
    licenseName: null,
    genre: "electronic/house",
    bpm: null,
    speed: null,
    vocalInstrumental: null,
    tags: ["electronic/house","cowbell","videogame","dark","energetic"],
    popularityWeek: 0,
    popularityTotal: 0,
    listensTotal: 0,
    downloadsTotal: 0,
    releaseDate: null,
    audioDownloadAllowed: true,
  },
  {
    id: "2313989",
    name: "Winter Came Early",
    duration: 110,
    artistId: "artist-infraction",
    artistName: "Infraction",
    albumId: "",
    albumName: "",
    audioUrl: "https://prod-1.storage.jamendo.com/?trackid=2313989&format=mp31&from=app-devsite",
    downloadUrl: "https://mp3d.jamendo.com/download/track/2313989/mp32/",
    image: "https://upcdn.io/12a1yuy/image/prd/public/QqutgONqMa/wuzs8zlHGCsw1YBm7ARLU.png",
    imageSmall: "https://upcdn.io/12a1yuy/image/prd/public/QqutgONqMa/wuzs8zlHGCsw1YBm7ARLU.png",
    licenseName: null,
    genre: "alternative",
    bpm: null,
    speed: null,
    vocalInstrumental: null,
    tags: ["alternative","happy","upbeat"],
    popularityWeek: 0,
    popularityTotal: 0,
    listensTotal: 0,
    downloadsTotal: 0,
    releaseDate: null,
    audioDownloadAllowed: true,
  },
  {
    id: "2292038",
    name: "Name Your Fear",
    duration: 93,
    artistId: "artist-soundrider-ysg",
    artistName: "Soundrider(YSG)",
    albumId: "",
    albumName: "",
    audioUrl: "https://prod-1.storage.jamendo.com/?trackid=2292038&format=mp31&from=app-devsite",
    downloadUrl: "https://mp3d.jamendo.com/download/track/2292038/mp32/",
    image: "https://upcdn.io/12a1yuy/image/prd/public/d1iYm0CxZv/JuKuLi1CBI49bTu2GDU4g.png",
    imageSmall: "https://upcdn.io/12a1yuy/image/prd/public/d1iYm0CxZv/JuKuLi1CBI49bTu2GDU4g.png",
    licenseName: null,
    genre: "rock/heavy metal",
    bpm: null,
    speed: null,
    vocalInstrumental: null,
    tags: ["rock/heavy metal","electricguitar","electroamplified","apocalyptic","neutral","dark"],
    popularityWeek: 0,
    popularityTotal: 0,
    listensTotal: 0,
    downloadsTotal: 0,
    releaseDate: null,
    audioDownloadAllowed: true,
  },
  {
    id: "1978673",
    name: "Phonk Emotion",
    duration: 80,
    artistId: "artist-alexzavesa",
    artistName: "AlexZavesa",
    albumId: "499027",
    albumName: "",
    audioUrl: "https://prod-1.storage.jamendo.com/?trackid=1978673&format=mp31&from=app-devsite",
    downloadUrl: "https://mp3d.jamendo.com/download/track/1978673/mp32/",
    image: "https://usercontent.jamendo.com/?type=album&id=499027&width=300&trackid=1978673",
    imageSmall: "https://usercontent.jamendo.com/?type=album&id=499027&width=300&trackid=1978673",
    licenseName: null,
    genre: "electronic",
    bpm: 128,
    speed: null,
    vocalInstrumental: null,
    tags: ["electronic","synthesizer","cowbell","videogame","emotional"],
    popularityWeek: 0,
    popularityTotal: 0,
    listensTotal: 0,
    downloadsTotal: 0,
    releaseDate: null,
    audioDownloadAllowed: true,
  },
  {
    id: "2214083",
    name: "Cloud City",
    duration: 76,
    artistId: "artist-infraction",
    artistName: "Infraction",
    albumId: "",
    albumName: "",
    audioUrl: "https://prod-1.storage.jamendo.com/?trackid=2214083&format=mp31&from=app-devsite",
    downloadUrl: "https://mp3d.jamendo.com/download/track/2214083/mp32/",
    image: "https://upcdn.io/12a1yuy/image/prd/public/QqutgONqMa/a0iNlCDzhG6dWTFtPdTam.png",
    imageSmall: "https://upcdn.io/12a1yuy/image/prd/public/QqutgONqMa/a0iNlCDzhG6dWTFtPdTam.png",
    licenseName: null,
    genre: "phonk",
    bpm: null,
    speed: null,
    vocalInstrumental: null,
    tags: ["hip-hop/rap","strings","bass","urban","sport","happy","energetic","powerful","aggressive"],
    popularityWeek: 0,
    popularityTotal: 0,
    listensTotal: 0,
    downloadsTotal: 0,
    releaseDate: null,
    audioDownloadAllowed: true,
  },
  {
    id: "2245280",
    name: "Bring It On",
    duration: 70,
    artistId: "artist-infraction",
    artistName: "Infraction",
    albumId: "",
    albumName: "",
    audioUrl: "https://prod-1.storage.jamendo.com/?trackid=2245280&format=mp31&from=app-devsite",
    downloadUrl: "https://mp3d.jamendo.com/download/track/2245280/mp32/",
    image: "https://upcdn.io/12a1yuy/image/prd/public/QqutgONqMa/mPVruJUNRclYz8Li85a1U.png",
    imageSmall: "https://upcdn.io/12a1yuy/image/prd/public/QqutgONqMa/mPVruJUNRclYz8Li85a1U.png",
    licenseName: null,
    genre: "phonk",
    bpm: null,
    speed: null,
    vocalInstrumental: null,
    tags: ["hip-hop/rap","strings","bass","urban","dark","energetic","aggressive"],
    popularityWeek: 0,
    popularityTotal: 0,
    listensTotal: 0,
    downloadsTotal: 0,
    releaseDate: null,
    audioDownloadAllowed: true,
  },
  {
    id: "2305060",
    name: "Shanghai Nights",
    duration: 69,
    artistId: "artist-infraction",
    artistName: "Infraction",
    albumId: "",
    albumName: "",
    audioUrl: "https://prod-1.storage.jamendo.com/?trackid=2305060&format=mp31&from=app-devsite",
    downloadUrl: "https://mp3d.jamendo.com/download/track/2305060/mp32/",
    image: "https://upcdn.io/12a1yuy/image/prd/public/QqutgONqMa/Fzh6A1GbnWCUFGtR9wE5q.png",
    imageSmall: "https://upcdn.io/12a1yuy/image/prd/public/QqutgONqMa/Fzh6A1GbnWCUFGtR9wE5q.png",
    licenseName: null,
    genre: "phonk",
    bpm: null,
    speed: null,
    vocalInstrumental: null,
    tags: ["hip-hop/rap","wind","brass","advertising","happy","powerful","aggressive"],
    popularityWeek: 0,
    popularityTotal: 0,
    listensTotal: 0,
    downloadsTotal: 0,
    releaseDate: null,
    audioDownloadAllowed: true,
  },
  {
    id: "2223830",
    name: "Urban Trap Phonk Beat",
    duration: 60,
    artistId: "artist-joel-loopez",
    artistName: "Joel Loopez",
    albumId: "",
    albumName: "",
    audioUrl: "https://prod-1.storage.jamendo.com/?trackid=2223830&format=mp31&from=app-devsite",
    downloadUrl: "https://mp3d.jamendo.com/download/track/2223830/mp32/",
    image: "https://upcdn.io/12a1yuy/image/prd/public/cM4KyhObr1/N23DBOMHxlUbRIhfpNvGk.png",
    imageSmall: "https://upcdn.io/12a1yuy/image/prd/public/cM4KyhObr1/N23DBOMHxlUbRIhfpNvGk.png",
    licenseName: null,
    genre: "phonk",
    bpm: null,
    speed: null,
    vocalInstrumental: null,
    tags: ["hip-hop/rap","aggressive"],
    popularityWeek: 0,
    popularityTotal: 0,
    listensTotal: 0,
    downloadsTotal: 0,
    releaseDate: null,
    audioDownloadAllowed: true,
  },
];
