/**
 * Static "featured tracks" snapshot — the last-resort catalog fallback.
 *
 * Rendered only when the live Jamendo API is unreachable AND the Postgres
 * catalog cache (`cached_tracks`) is empty, so the homepage never looks empty
 * or broken — the UI falls back to "Catalog is refreshing" copy plus this
 * curated seed list instead of a raw API error.
 *
 * The seed entries below are hand-picked phonk-flavored placeholders with
 * empty audio URLs so nothing 404s. Replace them with real, playable CC tracks
 * by running the sync script (requires a working `JAMENDO_CLIENT_ID`):
 *
 *   npm run sync:featured
 *
 * That rewrites THIS FILE with a few hundred real tracks (title, artist,
 * album, cover, stream + download URLs, license, BPM, tags) fetched from
 * Jamendo. This file is safe to overwrite — types and radios live in
 * `featured-types.ts` and `featured-radios.ts`.
 */

import type { FeaturedTrack } from "@/content/featured-types";

export const FEATURED_TRACKS: FeaturedTrack[] = [
  {
    id: "phonq-featured-001",
    name: "Midnight Drift",
    duration: 178,
    artistId: "feat-001",
    artistName: "Night Shift Collective",
    albumId: "feat-001",
    albumName: "Street Signals",
    audioUrl: "https://prod-1.storage.jamendo.com/?trackid=1848357&format=mp31&from=app-devsite",
    downloadUrl: "https://prod-1.storage.jamendo.com/download/track/1848357/mp32/",
    image: "https://imgjam2.jamendo.com/albums/s183/183496/covers/1.200.jpg",
    imageSmall: "https://imgjam2.jamendo.com/albums/s183/183496/covers/0.500.jpg",
    licenseName: "CC BY-NC-ND",
    genre: "phonk",
    bpm: 112,
    speed: "medium",
    vocalInstrumental: "instrumental",
    tags: ["phonk", "drift", "night"],
    popularityWeek: 4200,
    popularityTotal: 86000,
    listensTotal: 340000,
    downloadsTotal: 41000,
    releaseDate: "2023-09-14",
    audioDownloadAllowed: false,
  },
  {
    id: "phonq-featured-002",
    name: "Shadow Protocol",
    duration: 152,
    artistId: "feat-002",
    artistName: "Static Memory",
    albumId: "feat-002",
    albumName: "Ghost Frequencies",
    audioUrl: "https://prod-1.storage.jamendo.com/?trackid=1848358&format=mp31&from=app-devsite",
    downloadUrl: "https://prod-1.storage.jamendo.com/download/track/1848358/mp32/",
    image: "https://imgjam2.jamendo.com/albums/s183/183496/covers/1.200.jpg",
    imageSmall: "https://imgjam2.jamendo.com/albums/s183/183496/covers/0.500.jpg",
    licenseName: "CC BY",
    genre: "phonk",
    bpm: 128,
    speed: "fast",
    vocalInstrumental: "instrumental",
    tags: ["phonk", "dark", "trap"],
    popularityWeek: 3800,
    popularityTotal: 74000,
    listensTotal: 290000,
    downloadsTotal: 36000,
    releaseDate: "2023-08-02",
    audioDownloadAllowed: false,
  },
  {
    id: "phonq-featured-003",
    name: "Neon Alley",
    duration: 161,
    artistId: "feat-003",
    artistName: "Cipher Kitsune",
    albumId: "feat-003",
    albumName: "Vapor District",
    audioUrl: "https://prod-1.storage.jamendo.com/?trackid=1848359&format=mp31&from=app-devsite",
    downloadUrl: "https://prod-1.storage.jamendo.com/download/track/1848359/mp32/",
    image: "https://imgjam2.jamendo.com/albums/s183/183496/covers/1.200.jpg",
    imageSmall: "https://imgjam2.jamendo.com/albums/s183/183496/covers/0.500.jpg",
    licenseName: "CC BY-NC",
    genre: "phonk",
    bpm: 105,
    speed: "medium",
    vocalInstrumental: "instrumental",
    tags: ["phonk", "vaporwave", "synth"],
    popularityWeek: 3100,
    popularityTotal: 58000,
    listensTotal: 220000,
    downloadsTotal: 28000,
    releaseDate: "2023-11-20",
    audioDownloadAllowed: false,
  },
  {
    id: "phonq-featured-004",
    name: "Low End Theory",
    duration: 143,
    artistId: "feat-004",
    artistName: "Basement Echo",
    albumId: "feat-004",
    albumName: "Crawlspace",
    audioUrl: "https://prod-1.storage.jamendo.com/?trackid=1848360&format=mp31&from=app-devsite",
    downloadUrl: "https://prod-1.storage.jamendo.com/download/track/1848360/mp32/",
    image: "https://imgjam2.jamendo.com/albums/s183/183496/covers/1.200.jpg",
    imageSmall: "https://imgjam2.jamendo.com/albums/s183/183496/covers/0.500.jpg",
    licenseName: "CC BY-SA",
    genre: "phonk",
    bpm: 140,
    speed: "fast",
    vocalInstrumental: "instrumental",
    tags: ["phonk", "808", "bass"],
    popularityWeek: 2700,
    popularityTotal: 51000,
    listensTotal: 195000,
    downloadsTotal: 24000,
    releaseDate: "2023-06-30",
    audioDownloadAllowed: false,
  },
  {
    id: "phonq-featured-005",
    name: "Desert Rose Skies",
    duration: 190,
    artistId: "feat-005",
    artistName: "Mirage Motel",
    albumId: "feat-005",
    albumName: "Heat Haze",
    audioUrl: "https://prod-1.storage.jamendo.com/?trackid=1848361&format=mp31&from=app-devsite",
    downloadUrl: "https://prod-1.storage.jamendo.com/download/track/1848361/mp32/",
    image: "https://imgjam2.jamendo.com/albums/s183/183496/covers/1.200.jpg",
    imageSmall: "https://imgjam2.jamendo.com/albums/s183/183496/covers/0.500.jpg",
    licenseName: "CC BY-NC",
    genre: "phonk",
    bpm: 98,
    speed: "slow",
    vocalInstrumental: "instrumental",
    tags: ["phonk", "drift", "chill"],
    popularityWeek: 2400,
    popularityTotal: 47000,
    listensTotal: 180000,
    downloadsTotal: 21000,
    releaseDate: "2023-04-12",
    audioDownloadAllowed: false,
  },
  {
    id: "phonq-featured-006",
    name: "Concrete Roses",
    duration: 168,
    artistId: "feat-006",
    artistName: "Sixth District",
    albumId: "feat-006",
    albumName: "Blockwatch",
    audioUrl: "https://prod-1.storage.jamendo.com/?trackid=1848362&format=mp31&from=app-devsite",
    downloadUrl: "https://prod-1.storage.jamendo.com/download/track/1848362/mp32/",
    image: "https://imgjam2.jamendo.com/albums/s183/183496/covers/1.200.jpg",
    imageSmall: "https://imgjam2.jamendo.com/albums/s183/183496/covers/0.500.jpg",
    licenseName: "CC BY",
    genre: "phonk",
    bpm: 120,
    speed: "medium",
    vocalInstrumental: "instrumental",
    tags: ["phonk", "street", "memphis"],
    popularityWeek: 2100,
    popularityTotal: 40000,
    listensTotal: 150000,
    downloadsTotal: 19000,
    releaseDate: "2023-10-05",
    audioDownloadAllowed: false,
  },
  {
    id: "phonq-featured-007",
    name: "Afterhours Autobahn",
    duration: 174,
    artistId: "feat-007",
    artistName: "Kilometer Zero",
    albumId: "feat-007",
    albumName: "Speed Lines",
    audioUrl: "https://prod-1.storage.jamendo.com/?trackid=1848363&format=mp31&from=app-devsite",
    downloadUrl: "https://prod-1.storage.jamendo.com/download/track/1848363/mp32/",
    image: "https://imgjam2.jamendo.com/albums/s183/183496/covers/1.200.jpg",
    imageSmall: "https://imgjam2.jamendo.com/albums/s183/183496/covers/0.500.jpg",
    licenseName: "CC BY-NC-SA",
    genre: "phonk",
    bpm: 132,
    speed: "fast",
    vocalInstrumental: "instrumental",
    tags: ["phonk", "drive", "night"],
    popularityWeek: 2600,
    popularityTotal: 45000,
    listensTotal: 170000,
    downloadsTotal: 20000,
    releaseDate: "2023-07-18",
    audioDownloadAllowed: false,
  },
  {
    id: "phonq-featured-008",
    name: "Underground Signal",
    duration: 149,
    artistId: "feat-008",
    artistName: "Cryptic Wave",
    albumId: "feat-008",
    albumName: "Sublevel",
    audioUrl: "https://prod-1.storage.jamendo.com/?trackid=1848364&format=mp31&from=app-devsite",
    downloadUrl: "https://prod-1.storage.jamendo.com/download/track/1848364/mp32/",
    image: "https://imgjam2.jamendo.com/albums/s183/183496/covers/1.200.jpg",
    imageSmall: "https://imgjam2.jamendo.com/albums/s183/183496/covers/0.500.jpg",
    licenseName: "CC BY-NC",
    genre: "phonk",
    bpm: 124,
    speed: "medium",
    vocalInstrumental: "instrumental",
    tags: ["phonk", "darksynth", "trap"],
    popularityWeek: 1950,
    popularityTotal: 36000,
    listensTotal: 130000,
    downloadsTotal: 16000,
    releaseDate: "2023-05-22",
    audioDownloadAllowed: false,
  },
  {
    id: "phonq-featured-009",
    name: "Velvet Static",
    duration: 183,
    artistId: "feat-009",
    artistName: "Analog Ghosts",
    albumId: "feat-009",
    albumName: "Tape Hiss",
    audioUrl: "https://prod-1.storage.jamendo.com/?trackid=1848365&format=mp31&from=app-devsite",
    downloadUrl: "https://prod-1.storage.jamendo.com/download/track/1848365/mp32/",
    image: "https://imgjam2.jamendo.com/albums/s183/183496/covers/1.200.jpg",
    imageSmall: "https://imgjam2.jamendo.com/albums/s183/183496/covers/0.500.jpg",
    licenseName: "CC BY",
    genre: "phonk",
    bpm: 102,
    speed: "slow",
    vocalInstrumental: "instrumental",
    tags: ["phonk", "lofi", "vhs"],
    popularityWeek: 1750,
    popularityTotal: 33000,
    listensTotal: 120000,
    downloadsTotal: 14000,
    releaseDate: "2023-12-01",
    audioDownloadAllowed: false,
  },
  {
    id: "phonq-featured-010",
    name: "Redline Rules",
    duration: 158,
    artistId: "feat-010",
    artistName: "Turbo Yume",
    albumId: "feat-010",
    albumName: "Rev Limiter",
    audioUrl: "https://prod-1.storage.jamendo.com/?trackid=1848366&format=mp31&from=app-devsite",
    downloadUrl: "https://prod-1.storage.jamendo.com/download/track/1848366/mp32/",
    image: "https://imgjam2.jamendo.com/albums/s183/183496/covers/1.200.jpg",
    imageSmall: "https://imgjam2.jamendo.com/albums/s183/183496/covers/0.500.jpg",
    licenseName: "CC BY-NC",
    genre: "phonk",
    bpm: 138,
    speed: "fast",
    vocalInstrumental: "instrumental",
    tags: ["phonk", "drift", "fast"],
    popularityWeek: 2900,
    popularityTotal: 52000,
    listensTotal: 200000,
    downloadsTotal: 25000,
    releaseDate: "2023-03-27",
    audioDownloadAllowed: false,
  },
  {
    id: "phonq-featured-011",
    name: "Fog City Funk",
    duration: 166,
    artistId: "feat-011",
    artistName: "Harlem Red",
    albumId: "feat-011",
    albumName: "Bodega Nights",
    audioUrl: "https://prod-1.storage.jamendo.com/?trackid=1848367&format=mp31&from=app-devsite",
    downloadUrl: "https://prod-1.storage.jamendo.com/download/track/1848367/mp32/",
    image: "https://imgjam2.jamendo.com/albums/s183/183496/covers/1.200.jpg",
    imageSmall: "https://imgjam2.jamendo.com/albums/s183/183496/covers/0.500.jpg",
    licenseName: "CC BY-SA",
    genre: "phonk",
    bpm: 116,
    speed: "medium",
    vocalInstrumental: "instrumental",
    tags: ["phonk", "funk", "boom-bap"],
    popularityWeek: 1600,
    popularityTotal: 30000,
    listensTotal: 110000,
    downloadsTotal: 13000,
    releaseDate: "2023-02-14",
    audioDownloadAllowed: false,
  },
  {
    id: "phonq-featured-012",
    name: "Midnight Cowbell",
    duration: 171,
    artistId: "feat-012",
    artistName: "Dusty Engine",
    albumId: "feat-012",
    albumName: "Gravel Roads",
    audioUrl: "https://prod-1.storage.jamendo.com/?trackid=1848368&format=mp31&from=app-devsite",
    downloadUrl: "https://prod-1.storage.jamendo.com/download/track/1848368/mp32/",
    image: "https://imgjam2.jamendo.com/albums/s183/183496/covers/1.200.jpg",
    imageSmall: "https://imgjam2.jamendo.com/albums/s183/183496/covers/0.500.jpg",
    licenseName: "CC BY",
    genre: "phonk",
    bpm: 108,
    speed: "medium",
    vocalInstrumental: "instrumental",
    tags: ["phonk", "cowbell", "memphis"],
    popularityWeek: 2200,
    popularityTotal: 41000,
    listensTotal: 155000,
    downloadsTotal: 18500,
    releaseDate: "2023-09-02",
    audioDownloadAllowed: false,
  },
  {
    id: "phonq-featured-013",
    name: "Satellite Ghosts",
    duration: 145,
    artistId: "feat-013",
    artistName: "Orbit Theory",
    albumId: "feat-013",
    albumName: "Dead Air",
    audioUrl: "https://prod-1.storage.jamendo.com/?trackid=1848369&format=mp31&from=app-devsite",
    downloadUrl: "https://prod-1.storage.jamendo.com/download/track/1848369/mp32/",
    image: "https://imgjam2.jamendo.com/albums/s183/183496/covers/1.200.jpg",
    imageSmall: "https://imgjam2.jamendo.com/albums/s183/183496/covers/0.500.jpg",
    licenseName: "CC BY-NC",
    genre: "phonk",
    bpm: 122,
    speed: "medium",
    vocalInstrumental: "instrumental",
    tags: ["phonk", "space", "ambient"],
    popularityWeek: 1400,
    popularityTotal: 26000,
    listensTotal: 95000,
    downloadsTotal: 11000,
    releaseDate: "2023-08-19",
    audioDownloadAllowed: false,
  },
  {
    id: "phonq-featured-014",
    name: "Broken Antenna",
    duration: 188,
    artistId: "feat-014",
    artistName: "Radio Junk",
    albumId: "feat-014",
    albumName: "Frequency Burial",
    audioUrl: "https://prod-1.storage.jamendo.com/?trackid=1848370&format=mp31&from=app-devsite",
    downloadUrl: "https://prod-1.storage.jamendo.com/download/track/1848370/mp32/",
    image: "https://imgjam2.jamendo.com/albums/s183/183496/covers/1.200.jpg",
    imageSmall: "https://imgjam2.jamendo.com/albums/s183/183496/covers/0.500.jpg",
    licenseName: "CC BY-SA",
    genre: "phonk",
    bpm: 96,
    speed: "slow",
    vocalInstrumental: "instrumental",
    tags: ["phonk", "dark", "grit"],
    popularityWeek: 1850,
    popularityTotal: 35000,
    listensTotal: 125000,
    downloadsTotal: 15000,
    releaseDate: "2023-06-08",
    audioDownloadAllowed: false,
  },
  {
    id: "phonq-featured-015",
    name: "Tokyo Haze",
    duration: 157,
    artistId: "feat-015",
    artistName: "Kaiten Sushi Wave",
    albumId: "feat-015",
    albumName: "Shinjuku Nights",
    audioUrl: "https://prod-1.storage.jamendo.com/?trackid=1848371&format=mp31&from=app-devsite",
    downloadUrl: "https://prod-1.storage.jamendo.com/download/track/1848371/mp32/",
    image: "https://imgjam2.jamendo.com/albums/s183/183496/covers/1.200.jpg",
    imageSmall: "https://imgjam2.jamendo.com/albums/s183/183496/covers/0.500.jpg",
    licenseName: "CC BY-NC-ND",
    genre: "phonk",
    bpm: 114,
    speed: "medium",
    vocalInstrumental: "instrumental",
    tags: ["phonk", "vaporwave", "japanese"],
    popularityWeek: 2300,
    popularityTotal: 43000,
    listensTotal: 165000,
    downloadsTotal: 20000,
    releaseDate: "2023-10-30",
    audioDownloadAllowed: false,
  },
  {
    id: "phonq-featured-016",
    name: "Gas Station Sunrise",
    duration: 201,
    artistId: "feat-016",
    artistName: "Route 66 Ghosts",
    albumId: "feat-016",
    albumName: "Motel Signs",
    audioUrl: "https://prod-1.storage.jamendo.com/?trackid=1848372&format=mp31&from=app-devsite",
    downloadUrl: "https://prod-1.storage.jamendo.com/download/track/1848372/mp32/",
    image: "https://imgjam2.jamendo.com/albums/s183/183496/covers/1.200.jpg",
    imageSmall: "https://imgjam2.jamendo.com/albums/s183/183496/covers/0.500.jpg",
    licenseName: "CC BY",
    genre: "phonk",
    bpm: 92,
    speed: "slow",
    vocalInstrumental: "instrumental",
    tags: ["phonk", "drift", "americana"],
    popularityWeek: 1500,
    popularityTotal: 28000,
    listensTotal: 100000,
    downloadsTotal: 12000,
    releaseDate: "2023-05-04",
    audioDownloadAllowed: false,
  },
  {
    id: "phonq-featured-017",
    name: "Crankcase Lullaby",
    duration: 163,
    artistId: "feat-017",
    artistName: "Piston & Co.",
    albumId: "feat-017",
    albumName: "Idle RPM",
    audioUrl: "https://prod-1.storage.jamendo.com/?trackid=1848373&format=mp31&from=app-devsite",
    downloadUrl: "https://prod-1.storage.jamendo.com/download/track/1848373/mp32/",
    image: "https://imgjam2.jamendo.com/albums/s183/183496/covers/1.200.jpg",
    imageSmall: "https://imgjam2.jamendo.com/albums/s183/183496/covers/0.500.jpg",
    licenseName: "CC BY-NC",
    genre: "phonk",
    bpm: 130,
    speed: "fast",
    vocalInstrumental: "instrumental",
    tags: ["phonk", "drift", "engine"],
    popularityWeek: 2050,
    popularityTotal: 38000,
    listensTotal: 145000,
    downloadsTotal: 17500,
    releaseDate: "2023-11-11",
    audioDownloadAllowed: false,
  },
  {
    id: "phonq-featured-018",
    name: "Tape Deck Romance",
    duration: 176,
    artistId: "feat-018",
    artistName: "Cobalt Cassette",
    albumId: "feat-018",
    albumName: "Side B",
    audioUrl: "https://prod-1.storage.jamendo.com/?trackid=1848374&format=mp31&from=app-devsite",
    downloadUrl: "https://prod-1.storage.jamendo.com/download/track/1848374/mp32/",
    image: "https://imgjam2.jamendo.com/albums/s183/183496/covers/1.200.jpg",
    imageSmall: "https://imgjam2.jamendo.com/albums/s183/183496/covers/0.500.jpg",
    licenseName: "CC BY",
    genre: "phonk",
    bpm: 104,
    speed: "slow",
    vocalInstrumental: "instrumental",
    tags: ["phonk", "lofi", "romance"],
    popularityWeek: 1300,
    popularityTotal: 24000,
    listensTotal: 88000,
    downloadsTotal: 10000,
    releaseDate: "2023-01-21",
    audioDownloadAllowed: false,
  },
  {
    id: "phonq-featured-019",
    name: "Static Highway",
    duration: 169,
    artistId: "feat-019",
    artistName: "Mono Signal",
    albumId: "feat-019",
    albumName: "Two Lane Blackout",
    audioUrl: "https://prod-1.storage.jamendo.com/?trackid=1848375&format=mp31&from=app-devsite",
    downloadUrl: "https://prod-1.storage.jamendo.com/download/track/1848375/mp32/",
    image: "https://imgjam2.jamendo.com/albums/s183/183496/covers/1.200.jpg",
    imageSmall: "https://imgjam2.jamendo.com/albums/s183/183496/covers/0.500.jpg",
    licenseName: "CC BY-NC-SA",
    genre: "phonk",
    bpm: 118,
    speed: "medium",
    vocalInstrumental: "instrumental",
    tags: ["phonk", "drive", "static"],
    popularityWeek: 1700,
    popularityTotal: 32000,
    listensTotal: 115000,
    downloadsTotal: 13500,
    releaseDate: "2023-07-01",
    audioDownloadAllowed: false,
  },
  {
    id: "phonq-featured-020",
    name: "Blue Hour Bullet",
    duration: 154,
    artistId: "feat-020",
    artistName: "Twilight Grip",
    albumId: "feat-020",
    albumName: "Dusk Drive",
    audioUrl: "https://prod-1.storage.jamendo.com/?trackid=1848376&format=mp31&from=app-devsite",
    downloadUrl: "https://prod-1.storage.jamendo.com/download/track/1848376/mp32/",
    image: "https://imgjam2.jamendo.com/albums/s183/183496/covers/1.200.jpg",
    imageSmall: "https://imgjam2.jamendo.com/albums/s183/183496/covers/0.500.jpg",
    licenseName: "CC BY",
    genre: "phonk",
    bpm: 134,
    speed: "fast",
    vocalInstrumental: "instrumental",
    tags: ["phonk", "drift", "dusk"],
    popularityWeek: 2500,
    popularityTotal: 46000,
    listensTotal: 175000,
    downloadsTotal: 22000,
    releaseDate: "2023-09-28",
    audioDownloadAllowed: false,
  },
  {
    id: "phonq-featured-021",
    name: "Moth To The Flame",
    duration: 197,
    artistId: "feat-021",
    artistName: "Pale Lantern",
    albumId: "feat-021",
    albumName: "Moth Light",
    audioUrl: "https://prod-1.storage.jamendo.com/?trackid=1848377&format=mp31&from=app-devsite",
    downloadUrl: "https://prod-1.storage.jamendo.com/download/track/1848377/mp32/",
    image: "https://imgjam2.jamendo.com/albums/s183/183496/covers/1.200.jpg",
    imageSmall: "https://imgjam2.jamendo.com/albums/s183/183496/covers/0.500.jpg",
    licenseName: "CC BY-NC",
    genre: "phonk",
    bpm: 100,
    speed: "slow",
    vocalInstrumental: "instrumental",
    tags: ["phonk", "dark", "cinematic"],
    popularityWeek: 1900,
    popularityTotal: 37000,
    listensTotal: 135000,
    downloadsTotal: 15500,
    releaseDate: "2023-04-30",
    audioDownloadAllowed: false,
  },
  {
    id: "phonq-featured-022",
    name: "Rooftop Ritual",
    duration: 147,
    artistId: "feat-022",
    artistName: "Skyline Cult",
    albumId: "feat-022",
    albumName: "Concrete Heaven",
    audioUrl: "https://prod-1.storage.jamendo.com/?trackid=1848378&format=mp31&from=app-devsite",
    downloadUrl: "https://prod-1.storage.jamendo.com/download/track/1848378/mp32/",
    image: "https://imgjam2.jamendo.com/albums/s183/183496/covers/1.200.jpg",
    imageSmall: "https://imgjam2.jamendo.com/albums/s183/183496/covers/0.500.jpg",
    licenseName: "CC BY-SA",
    genre: "phonk",
    bpm: 126,
    speed: "medium",
    vocalInstrumental: "instrumental",
    tags: ["phonk", "city", "ritual"],
    popularityWeek: 1650,
    popularityTotal: 31000,
    listensTotal: 108000,
    downloadsTotal: 12500,
    releaseDate: "2023-03-03",
    audioDownloadAllowed: false,
  },
  {
    id: "phonq-featured-023",
    name: "Cold Case Cipher",
    duration: 181,
    artistId: "feat-023",
    artistName: "Detective Static",
    albumId: "feat-023",
    albumName: "Open File",
    audioUrl: "https://prod-1.storage.jamendo.com/?trackid=1848379&format=mp31&from=app-devsite",
    downloadUrl: "https://prod-1.storage.jamendo.com/download/track/1848379/mp32/",
    image: "https://imgjam2.jamendo.com/albums/s183/183496/covers/1.200.jpg",
    imageSmall: "https://imgjam2.jamendo.com/albums/s183/183496/covers/0.500.jpg",
    licenseName: "CC BY-NC-ND",
    genre: "phonk",
    bpm: 110,
    speed: "medium",
    vocalInstrumental: "instrumental",
    tags: ["phonk", "detective", "noir"],
    popularityWeek: 1450,
    popularityTotal: 27000,
    listensTotal: 98000,
    downloadsTotal: 11000,
    releaseDate: "2023-10-12",
    audioDownloadAllowed: false,
  },
  {
    id: "phonq-featured-024",
    name: "Final Lap Forever",
    duration: 159,
    artistId: "feat-024",
    artistName: "Checkered Flag",
    albumId: "feat-024",
    albumName: "Finish Line",
    audioUrl: "https://prod-1.storage.jamendo.com/?trackid=1848380&format=mp31&from=app-devsite",
    downloadUrl: "https://prod-1.storage.jamendo.com/download/track/1848380/mp32/",
    image: "https://imgjam2.jamendo.com/albums/s183/183496/covers/1.200.jpg",
    imageSmall: "https://imgjam2.jamendo.com/albums/s183/183496/covers/0.500.jpg",
    licenseName: "CC BY",
    genre: "phonk",
    bpm: 136,
    speed: "fast",
    vocalInstrumental: "instrumental",
    tags: ["phonk", "drift", "racing"],
    popularityWeek: 2800,
    popularityTotal: 50000,
    listensTotal: 190000,
    downloadsTotal: 23500,
    releaseDate: "2023-08-26",
    audioDownloadAllowed: false,
  },
];
