/**
 * Regenerates `src/content/featured-tracks.ts` with real, playable CC tracks
 * fetched from Jamendo, so the static homepage fallback stays fresh.
 *
 * Requires a working `JAMENDO_CLIENT_ID` in the environment:
 *
 *   npm run sync:featured
 *
 * Pulls a few hundred phonk tracks (paged), normalizes them, and rewrites the
 * snapshot file in place. Safe to run repeatedly — the file is overwritten.
 */
import "dotenv/config";
import * as fs from "node:fs";
import * as path from "node:path";
import { fileURLToPath } from "node:url";

const BASE_URL = "https://api.jamendo.com/v3.0";
const TARGET_COUNT = 300;

const DIR = path.dirname(fileURLToPath(import.meta.url));
const OUT_FILE = path.join(DIR, "..", "src", "content", "featured-tracks.ts");

interface JamendoTrack {
  id: string | number;
  name: string;
  duration: number;
  artist_id: string | number;
  artist_name: string;
  album_id: string | number;
  album_name: string;
  audio: string;
  audiodownload: string;
  image: string;
  image_small: string;
  license_name?: string;
  tags?: string;
  musicinfo?: { bpm?: number; genre?: string; speed?: string; vocalinstrumental?: string };
  stats?: {
    popularity_week?: number;
    popularity_month?: number;
    popularity_total?: number;
    listens_total?: number;
    downloads_total?: number;
  };
  releasedate?: string;
  audiodownload_allowed?: boolean;
}

async function fetchPage(offset: number, limit: number): Promise<JamendoTrack[]> {
  const params = new URLSearchParams({
    client_id: process.env.JAMENDO_CLIENT_ID ?? "",
    format: "json",
    fuzzytags: "phonk",
    boost: "popularity_week",
    order: "popularity_week_desc",
    limit: String(limit),
    offset: String(offset),
    include: "musicinfo,stats",
  });
  const res = await fetch(`${BASE_URL}/tracks/?${params.toString()}`, { cache: "no-store" });
  if (!res.ok) throw new Error(`Jamendo returned ${res.status}`);
  const body = (await res.json()) as {
    headers: { status: string; error_message?: string };
    results: JamendoTrack[];
  };
  if (body.headers.status !== "success") {
    throw new Error(body.headers.error_message ?? "Jamendo API error");
  }
  return body.results;
}

function toNumber(v: unknown): number {
  return typeof v === "number" && Number.isFinite(v) ? v : 0;
}

async function main(): Promise<void> {
  const clientId = process.env.JAMENDO_CLIENT_ID ?? "";
  if (!clientId || clientId === "709fa152") {
    console.error(
      "sync:featured needs a working JAMENDO_CLIENT_ID. The bundled '709fa152' test key is suspended.",
    );
    process.exit(1);
  }

  console.log(`Pulling up to ${TARGET_COUNT} real phonk tracks from Jamendo…`);

  const seen = new Map<string, JamendoTrack>();
  let offset = 0;

  while (seen.size < TARGET_COUNT && offset < 10_000) {
    const batch = await fetchPage(offset, 100);
    if (batch.length === 0) break;
    for (const track of batch) {
      if (!seen.has(String(track.id))) seen.set(String(track.id), track);
    }
    console.log(`  fetched ${Math.min(seen.size, TARGET_COUNT)} unique tracks…`);
    offset += batch.length;
  }

  const tracks = [...seen.values()]
    .slice(0, TARGET_COUNT)
    .map((t) => ({
      id: String(t.id),
      name: t.name || "Untitled",
      duration: Math.round(toNumber(t.duration)),
      artistId: String(t.artist_id ?? ""),
      artistName: t.artist_name || "Unknown Artist",
      albumId: String(t.album_id ?? ""),
      albumName: t.album_name || "Unknown Album",
      audioUrl: t.audio ?? "",
      downloadUrl: t.audiodownload ?? "",
      image: t.image || null,
      imageSmall: t.image_small || null,
      licenseName: t.license_name ?? null,
      genre: t.musicinfo?.genre ?? null,
      bpm: typeof t.musicinfo?.bpm === "number" ? t.musicinfo.bpm : null,
      speed: t.musicinfo?.speed ?? null,
      vocalInstrumental: t.musicinfo?.vocalinstrumental ?? null,
      tags: (t.tags ?? "").split(/\s+/).filter(Boolean),
      popularityWeek: toNumber(t.stats?.popularity_week),
      popularityTotal: toNumber(t.stats?.popularity_total),
      listensTotal: toNumber(t.stats?.listens_total),
      downloadsTotal: toNumber(t.stats?.downloads_total),
      releaseDate: t.releasedate ?? null,
      audioDownloadAllowed: Boolean(t.audiodownload_allowed),
    }))
    .sort((a, b) => b.popularityWeek - a.popularityWeek);

  if (tracks.length === 0) throw new Error("No tracks returned — is the API reachable?");

  const header = `/**
 * AUTO-GENERATED by \`npm run sync:featured\` — do not edit by hand.
 * Generated ${new Date().toISOString()} · ${tracks.length} tracks · sourced from
 * the Jamendo API (CC-licensed). Replaces the hand-curated seed list used as the
 * last-resort static catalog fallback. Types live in \`featured-types.ts\`.
 */
`;

  const body =
    'import type { FeaturedTrack } from "@/content/featured-types";\n\n' +
    "export const FEATURED_TRACKS: FeaturedTrack[] = " +
    JSON.stringify(tracks, null, 2) +
    ";\n";

  fs.writeFileSync(OUT_FILE, header + body);
  console.log(`Wrote ${tracks.length} tracks → ${OUT_FILE}`);
}

try {
  main();
} catch (err) {
  console.error(err instanceof Error ? err.message : err);
  process.exit(1);
}
